//! Text primitives with Python semantics: case folding, whitespace, line splitting and
//! the token stream of the old engine.
//!
//! The old engine ran on Python's `str` methods and `re` classes. Their exact character
//! sets come from `python_unicode.txt`, generated by `tools/eval/legacy_baseline.py
//! unicode`, so no behaviour depends on the Unicode version of the Rust toolchain.

use std::sync::LazyLock;

use super::lexicon;

struct Tables {
    /// Non-ASCII ranges of Python's `\w`.
    word: Vec<(u32, u32)>,
    /// Ranges of Python's `\d`; each run counts 0-9 from its start.
    digit: Vec<(u32, u32)>,
    /// `str.casefold()` for every code point it changes, sorted.
    fold: Vec<(u32, Box<str>)>,
}

static TABLES: LazyLock<Tables> =
    LazyLock::new(|| parse_tables(include_str!("python_unicode.txt")));

fn parse_tables(data: &str) -> Tables {
    let hex = |s: &str| u32::from_str_radix(s, 16).expect("hex code point in python_unicode.txt");
    let mut tables = Tables {
        word: Vec::new(),
        digit: Vec::new(),
        fold: Vec::new(),
    };
    for line in data
        .lines()
        .filter(|l| !l.starts_with('#') && !l.is_empty())
    {
        let mut parts = line.split(' ');
        let kind = parts.next().unwrap_or_default();
        let first = hex(parts.next().unwrap_or_default());
        match kind {
            "w" => tables
                .word
                .push((first, hex(parts.next().unwrap_or_default()))),
            "d" => tables
                .digit
                .push((first, hex(parts.next().unwrap_or_default()))),
            "f" => {
                let folded: String = parts.filter_map(|p| char::from_u32(hex(p))).collect();
                tables.fold.push((first, folded.into_boxed_str()));
            }
            _ => {}
        }
    }
    tables
}

fn in_ranges(ranges: &[(u32, u32)], c: char) -> Option<(u32, u32)> {
    let cp = u32::from(c);
    let i = ranges.partition_point(|&(_, end)| end < cp);
    ranges.get(i).copied().filter(|&(start, _)| start <= cp)
}

/// Python `str.isspace()` (and `re` `\s`).
pub(crate) fn is_space(c: char) -> bool {
    matches!(
        c,
        '\t'..='\r'
            | '\x1c'..='\x1f'
            | ' '
            | '\u{85}'
            | '\u{a0}'
            | '\u{1680}'
            | '\u{2000}'..='\u{200a}'
            | '\u{2028}'
            | '\u{2029}'
            | '\u{202f}'
            | '\u{205f}'
            | '\u{3000}'
    )
}

/// Python `re` `\w` (`str.isalnum()` or `_`).
pub(crate) fn is_word(c: char) -> bool {
    if c.is_ascii() {
        c.is_ascii_alphanumeric() || c == '_'
    } else {
        in_ranges(&TABLES.word, c).is_some()
    }
}

/// Value of a Python decimal digit (`re` `\d`), any script.
pub(crate) fn decimal(c: char) -> Option<u32> {
    if c.is_ascii() {
        return c.to_digit(10);
    }
    in_ranges(&TABLES.digit, c).map(|(start, _)| (u32::from(c) - start) % 10)
}

/// Body of a regex character class matching exactly Python's `\d`.
pub(crate) fn digit_class_body() -> String {
    use std::fmt::Write as _;
    TABLES.digit.iter().fold(String::new(), |mut out, &(a, b)| {
        let _ = write!(out, "\\x{{{a:X}}}-\\x{{{b:X}}}");
        out
    })
}

/// Python `str.casefold()`.
pub(crate) fn casefold(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        push_folded(&mut out, c);
    }
    out
}

fn push_folded(out: &mut String, c: char) {
    if c.is_ascii() {
        out.push(c.to_ascii_lowercase());
        return;
    }
    let cp = u32::from(c);
    match TABLES.fold.binary_search_by_key(&cp, |(k, _)| *k) {
        Ok(i) => out.push_str(&TABLES.fold[i].1),
        Err(_) => out.push(c),
    }
}

/// Case-folded text plus, for every byte of the result, the byte offset of the source
/// character it came from (to map matches back for highlights).
#[allow(dead_code)] // Used by the engine API.
pub(crate) fn casefold_mapped(text: &str) -> (String, Vec<usize>) {
    let mut out = String::with_capacity(text.len());
    let mut origin = Vec::with_capacity(text.len());
    for (at, c) in text.char_indices() {
        let before = out.len();
        push_folded(&mut out, c);
        origin.resize(out.len(), at);
        debug_assert!(out.len() >= before);
    }
    origin.push(text.len());
    (out, origin)
}

/// Python `str.strip()`.
pub(crate) fn strip(text: &str) -> &str {
    text.trim_matches(is_space)
}

/// Python `str.rstrip()`.
pub(crate) fn rstrip(text: &str) -> &str {
    text.trim_end_matches(is_space)
}

/// Python `str.split()` without arguments.
pub(crate) fn split_whitespace(text: &str) -> impl Iterator<Item = &str> {
    text.split(is_space).filter(|part| !part.is_empty())
}

/// Python `str.splitlines()`: every Unicode line boundary, `\r\n` counts once, no
/// trailing empty line.
pub(crate) fn splitlines(text: &str) -> Vec<&str> {
    let mut lines = Vec::new();
    let mut start = 0;
    let mut chars = text.char_indices().peekable();
    while let Some((at, c)) = chars.next() {
        let is_break = matches!(
            c,
            '\n' | '\r'
                | '\x0b'
                | '\x0c'
                | '\x1c'
                | '\x1d'
                | '\x1e'
                | '\u{85}'
                | '\u{2028}'
                | '\u{2029}'
        );
        if !is_break {
            continue;
        }
        lines.push(&text[start..at]);
        let mut end = at + c.len_utf8();
        if c == '\r' && chars.peek().is_some_and(|&(_, next)| next == '\n') {
            chars.next();
            end += 1;
        }
        start = end;
    }
    if start < text.len() {
        lines.push(&text[start..]);
    }
    lines
}

/// Length in code points, like Python's `len(str)`.
pub(crate) fn char_len(text: &str) -> usize {
    text.chars().count()
}

fn is_token_start(c: char) -> bool {
    c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, 'ä' | 'ö' | 'ü' | 'ß' | '+' | '#')
}

fn is_token_char(c: char) -> bool {
    is_token_start(c) || matches!(c, '.' | '/' | '-')
}

/// Tokens of an already case-folded text: `[a-z0-9äöüß+#][a-z0-9äöüß+#./\-]*`, trailing
/// dots removed.
fn raw_token_iter(folded: &str) -> impl Iterator<Item = &str> {
    let mut rest = folded;
    std::iter::from_fn(move || {
        let start = rest.find(is_token_start)?;
        let tail = &rest[start..];
        let end = tail.find(|c| !is_token_char(c)).unwrap_or(tail.len());
        rest = &tail[end..];
        Some(tail[..end].trim_end_matches('.'))
    })
}

/// Python `_tokens`: case-folded tokens, at least three characters (or a known short
/// synonym key), without stopwords.
pub(crate) fn tokens(text: &str) -> Vec<String> {
    if text.is_empty() {
        return Vec::new();
    }
    let folded = casefold(text);
    raw_token_iter(&folded)
        .filter(|t| char_len(t) >= 3 || lexicon::synonym(t).is_some())
        .filter(|t| !lexicon::contains(lexicon::STOPWORDS, t))
        .map(str::to_owned)
        .collect()
}

/// Python `_raw_canonical`: tokens without the length filter, canonicalised.
pub(crate) fn raw_canonical(text: &str) -> Vec<String> {
    let folded = casefold(text);
    let tokens = raw_token_iter(&folded)
        .filter(|t| !lexicon::contains(lexicon::STOPWORDS, t))
        .map(str::to_owned)
        .collect();
    canonical_stream(tokens)
}

/// Python `canonical_stream`: word synonyms first, then adjacent pairs, left to right.
pub(crate) fn canonical_stream(tokens: Vec<String>) -> Vec<String> {
    let words: Vec<String> = tokens
        .into_iter()
        .filter_map(|t| match lexicon::synonym(&t) {
            Some(Some(mapped)) => Some(mapped.to_owned()),
            Some(None) => None,
            None => Some(t),
        })
        .collect();
    let mut result = Vec::with_capacity(words.len());
    let mut i = 0;
    while i < words.len() {
        if let Some(next) = words.get(i + 1)
            && let Some(merged) = lexicon::synonym_pair(&words[i], next)
        {
            result.push(merged.to_owned());
            i += 2;
            continue;
        }
        result.push(words[i].clone());
        i += 1;
    }
    result
}

/// Python `canonical_phrase`.
pub(crate) fn canonical_phrase(text: &str) -> String {
    canonical_stream(tokens(text)).join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn casefold_follows_python() {
        assert_eq!(casefold("GROẞKONZERN Straße"), "grosskonzern strasse");
        assert_eq!(
            casefold("Zertiﬁzierung İ ſ K"),
            "zertifizierung i\u{307} s k"
        );
        assert_eq!(casefold("ΣΑΣ"), "σασ");
    }

    #[test]
    fn python_character_classes() {
        assert!(is_space('\x1f') && is_space('\u{a0}') && !is_space('\u{200b}'));
        assert!(is_word('²') && is_word('ª') && !is_word('\u{200d}') && !is_word('\u{301}'));
        assert_eq!(decimal('\u{663}'), Some(3));
        assert_eq!(decimal('\u{1d7d8}'), Some(0));
        assert_eq!(decimal('²'), None);
    }

    #[test]
    fn splitlines_like_python() {
        assert_eq!(
            splitlines("a\r\nb\rc\u{2028}d\x0ce\n"),
            ["a", "b", "c", "d", "e"]
        );
        assert_eq!(splitlines("a\n\nb"), ["a", "", "b"]);
        assert_eq!(splitlines("\n"), [""]);
        assert!(splitlines("").is_empty());
        assert_eq!(splitlines("a\x1fb"), ["a\x1fb"]);
    }

    #[test]
    fn tokens_and_synonyms() {
        assert_eq!(
            tokens("SAP S4 HANA, KI und Power BI."),
            ["sap", "s4", "hana", "ki", "power", "bi"]
        );
        assert_eq!(canonical_phrase("SAP S4 HANA"), "sap s/4hana");
        assert_eq!(canonical_phrase("Project Management"), "projektmanagement");
        assert_eq!(canonical_phrase("z. B. LucaNet"), "lucanet");
    }
}
