//! Finance, controlling, accounting, treasury, restructuring and M&A.
//!
//! external contract - do not translate.

use super::Domain;

pub(crate) const DOMAIN: Domain = Domain {
    name: "finance",
    triggers: &[
        "accounting",
        "bilanz",
        "buchhalt",
        "budget",
        "carve-out",
        "cfo",
        "controll",
        "finanztransformation",
        "fp&a",
        "hauptbuch",
        "hgb",
        "ifrs",
        "jahresabschl",
        "konsolidier",
        "konzernabschluss",
        "konzernrechnungs",
        "kostenrechnung",
        "kostenstellen",
        "liquidit",
        "m&a",
        "monatsabschl",
        "rechnungslegung",
        "rechnungswesen",
        "restrukturier",
        "sanierung",
        "treasury",
    ],
    generic: &[],
    concepts: &[
        // Closings and statements.
        ("annual financial statement", "jahresabschluss"),
        ("annual accounts", "jahresabschluss"),
        ("year-end closing", "jahresabschluss"),
        ("year end closing", "jahresabschluss"),
        ("year-end close", "jahresabschluss"),
        ("month-end closing", "monatsabschluss"),
        ("month end closing", "monatsabschluss"),
        ("month-end close", "monatsabschluss"),
        ("monthly closing", "monatsabschluss"),
        ("monthly close", "monatsabschluss"),
        ("consolidated financial statement", "konzernabschluss"),
        ("group financial statement", "konzernabschluss"),
        // Group accounting and reporting.
        ("group accounting", "konzernrechnungslegung"),
        ("konzernrechnungswesen", "konzernrechnungslegung"),
        ("group reporting", "konzernreporting"),
        ("group controlling", "konzerncontrolling"),
        ("group consolidation", "konzernkonsolidierung"),
        ("group treasury", "konzerntreasury"),
        ("consolidation", "konsolidierung"),
        ("berichtswesen", "reporting"),
        // Finance leadership roles and paraphrases (held-out sets).
        ("finance director", "cfo"),
        ("director finance", "cfo"),
        ("chief financial officer", "cfo"),
        ("kaufmannischer leiter", "cfo"),
        ("kaufmannische leiterin", "cfo"),
        ("kaufmannische leitung", "cfo"),
        ("finanzleiter", "cfo"),
        ("finanzleiterin", "cfo"),
        ("leiter finanzen", "cfo"),
        ("leiterin finanzen", "cfo"),
        ("budget planning", "budgetierung"),
        ("turnaround", "restrukturierung"),
        ("sanierung", "restrukturierung"),
        ("krisensituation", "restrukturierung"),
        ("german gaap", "hgb"),
        ("us gaap", "us-gaap"),
        // Controlling and planning.
        ("financial planning analysis", "fp&a"),
        ("financial controlling", "controlling"),
        ("controller", "controlling"),
        ("finance business partner", "finance-bp"),
        ("finance business partnering", "finance-bp"),
        ("budgeting", "budgetierung"),
        ("budgetplanung", "budgetierung"),
        ("forecasting", "forecast"),
        ("hochrechnung", "forecast"),
        ("variance analysis", "abweichungsanalyse"),
        ("accruals", "abgrenzung"),
        ("soll-ist-vergleich", "abweichungsanalyse"),
        ("cost accounting", "kostenrechnung"),
        ("cost center accounting", "kostenstellenrechnung"),
        ("cost centre accounting", "kostenstellenrechnung"),
        ("product costing", "produktkostenrechnung"),
        ("profitability analysis", "ergebnisrechnung"),
        // Bookkeeping.
        ("financial accounting", "finanzbuchhaltung"),
        ("accounting", "rechnungswesen"),
        ("ledger", "hauptbuchhaltung"),
        ("accounts payable", "kreditorenbuchhaltung"),
        ("accounts receivable", "debitorenbuchhaltung"),
        ("fixed asset accounting", "anlagenbuchhaltung"),
        ("asset accounting", "anlagenbuchhaltung"),
        // Treasury and liquidity.
        ("liquidity planning", "liquiditatsplanung"),
        ("cash flow planning", "liquiditatsplanung"),
        ("cash forecast", "liquiditatsplanung"),
        ("cash management", "cash-management"),
        ("liquidity management", "cash-management"),
        ("liquiditatsmanagement", "cash-management"),
        ("liquiditatssteuerung", "cash-management"),
        ("working capital management", "working-capital-management"),
        ("working capital", "working-capital-management"),
        // Transactions and restructuring.
        ("post merger integration", "post-merger-integration"),
        ("pmi", "post-merger-integration"),
        ("mergers acquisitions", "m&a"),
        ("mergers acquisition", "m&a"),
        ("carve out", "carve-out"),
        ("restructuring", "restrukturierung"),
        ("shared service centre", "shared-service-cent"),
        ("shared service center", "shared-service-cent"),
    ],
};
