//! Human resources: HR leadership and transformation, labour law and co-determination,
//! recruiting, talent, compensation and payroll, HR systems.
//!
//! external contract - do not translate.

use super::Domain;

pub(crate) const DOMAIN: Domain = Domain {
    name: "hr",
    triggers: &[
        "arbeitsdirektor",
        "arbeitsrecht",
        "betriebsrat",
        "betriebsubergang",
        "betriebsvereinbarung",
        "betriebsverfassung",
        "chro",
        "compensation",
        "employer",
        "entgeltabrechn",
        "entgeltsystem",
        "fuhrungskrafteentwickl",
        "gehaltsabrechn",
        "hcm",
        "hr",
        "interessenausgleich",
        "lohnabrechn",
        "mitbestimmung",
        "nachfolgeplan",
        "payroll",
        "personalabteil",
        "personaladministr",
        "personalarbeit",
        "personalbeschaff",
        "personalcontroll",
        "personalentwickl",
        "personalgewinn",
        "personalleit",
        "personalmanagement",
        "personalmarketing",
        "personalplan",
        "personalreferent",
        "personalstrateg",
        "personalvorstand",
        "personalwesen",
        "personalwirtschaft",
        "recruit",
        "sozialplan",
        "stellenbewert",
        "successfactors",
        "talent",
        "tarifrecht",
        "tarifverhandl",
        "tarifvertr",
        "vergutungs",
        "workday",
    ],
    generic: &["people", "personal"],
    concepts: &[
        // The field itself.
        ("human resources", "hr"),
        ("human resources management", "hr"),
        ("hr management", "hr"),
        ("personalwesen", "hr"),
        ("personalmanagement", "hr"),
        ("personalabteilung", "hr"),
        ("people culture", "hr"),
        // Leadership roles, with the female forms the stemmer does not fold.
        ("personalleiter", "personalleitung"),
        ("personalleiterin", "personalleitung"),
        ("leiter personal", "personalleitung"),
        ("leiterin personal", "personalleitung"),
        ("leitung personal", "personalleitung"),
        ("leiter personalwesen", "personalleitung"),
        ("leiterin personalwesen", "personalleitung"),
        ("leitung personalwesen", "personalleitung"),
        ("leiter hr", "personalleitung"),
        ("leiterin hr", "personalleitung"),
        ("hr leiter", "personalleitung"),
        ("hr leiterin", "personalleitung"),
        ("hr leitung", "personalleitung"),
        ("head hr", "personalleitung"),
        ("head human resources", "personalleitung"),
        ("head people", "personalleitung"),
        ("hr director", "personalleitung"),
        ("director hr", "personalleitung"),
        ("director human resources", "personalleitung"),
        ("hr direktor", "personalleitung"),
        ("hr direktorin", "personalleitung"),
        ("personaldirektor", "personalleitung"),
        ("personaldirektorin", "personalleitung"),
        ("personalchef", "personalleitung"),
        ("personalchefin", "personalleitung"),
        ("chief human resources officer", "chro"),
        ("chief people officer", "chro"),
        ("chief hr officer", "chro"),
        ("personalvorstand", "chro"),
        ("personalvorstandin", "chro"),
        ("vorstand personal", "chro"),
        ("arbeitsdirektor", "chro"),
        ("arbeitsdirektorin", "chro"),
        ("hr business partner", "hrbusinesspartner"),
        ("hr business partnerin", "hrbusinesspartner"),
        ("human resources business partner", "hrbusinesspartner"),
        ("hrbp", "hrbusinesspartner"),
        ("personalreferentin", "personalreferent"),
        ("hr referent", "personalreferent"),
        ("hr referentin", "personalreferent"),
        ("hr generalist", "personalreferent"),
        ("hr generalistin", "personalreferent"),
        // Transformation and organisation.
        ("hr transformation", "hr-transformation"),
        ("personaltransformation", "hr-transformation"),
        ("hr business partner modell", "dreisaulenmodell"),
        ("drei saulen modell", "dreisaulenmodell"),
        ("three pillar model", "dreisaulenmodell"),
        ("hr strategy", "personalstrategie"),
        ("hr strategie", "personalstrategie"),
        ("people strategy", "personalstrategie"),
        ("organisational development", "organisationsentwicklung"),
        ("organizational development", "organisationsentwicklung"),
        ("organisation development", "organisationsentwicklung"),
        ("organization development", "organisationsentwicklung"),
        ("hr administration", "personaladministration"),
        ("hr operations", "personaladministration"),
        ("personnel administration", "personaladministration"),
        ("personalverwaltung", "personaladministration"),
        ("personalsachbearbeitung", "personaladministration"),
        // Recruiting and employer branding.
        ("recruitment", "recruiting"),
        ("recruiterin", "recruiting"),
        ("talent acquisition", "recruiting"),
        ("personalbeschaffung", "recruiting"),
        ("personalgewinnung", "recruiting"),
        ("personalrekrutierung", "recruiting"),
        ("rekrutierung", "recruiting"),
        ("mitarbeitergewinnung", "recruiting"),
        ("personalsuche", "recruiting"),
        // A recruiting method, not strategic sourcing in procurement.
        ("active sourcing", "direktansprache"),
        ("employer branding", "arbeitgebermarke"),
        ("arbeitgebermarketing", "arbeitgebermarke"),
        ("personalmarketing", "arbeitgebermarke"),
        ("einarbeitung", "onboarding"),
        ("assessment center", "eignungsdiagnostik"),
        ("assessment centre", "eignungsdiagnostik"),
        // Development and talent.
        ("personnel development", "personalentwicklung"),
        ("employee development", "personalentwicklung"),
        ("learning development", "personalentwicklung"),
        ("l&d", "personalentwicklung"),
        ("leadership development", "fuhrungskrafteentwicklung"),
        ("management development", "fuhrungskrafteentwicklung"),
        ("fuhrungsentwicklung", "fuhrungskrafteentwicklung"),
        ("talent management", "talentmanagement"),
        ("talententwicklung", "talentmanagement"),
        ("succession planning", "nachfolgeplanung"),
        ("succession management", "nachfolgeplanung"),
        ("nachfolgemanagement", "nachfolgeplanung"),
        ("performance management", "leistungsmanagement"),
        ("performance appraisal", "leistungsmanagement"),
        ("performance review", "leistungsmanagement"),
        ("leistungsbeurteilung", "leistungsmanagement"),
        // Compensation and payroll.
        ("compensation benefits", "vergutungsmanagement"),
        ("compensation management", "vergutungsmanagement"),
        ("c&b", "vergutungsmanagement"),
        ("total rewards", "vergutungsmanagement"),
        ("reward management", "vergutungsmanagement"),
        ("vergutungssystem", "vergutungsmanagement"),
        ("entgeltsystem", "vergutungsmanagement"),
        ("payroll", "entgeltabrechnung"),
        ("payroll accounting", "entgeltabrechnung"),
        ("lohnabrechnung", "entgeltabrechnung"),
        ("gehaltsabrechnung", "entgeltabrechnung"),
        ("lohn gehaltsabrechnung", "entgeltabrechnung"),
        ("lohnbuchhaltung", "entgeltabrechnung"),
        // Labour law, co-determination and restructuring.
        ("labour law", "arbeitsrecht"),
        ("labor law", "arbeitsrecht"),
        ("employment law", "arbeitsrecht"),
        ("arbeitsrechtlich", "arbeitsrecht"),
        ("works council", "betriebsrat"),
        ("arbeitnehmervertretung", "betriebsrat"),
        ("arbeitnehmervertreter", "betriebsrat"),
        ("betriebsverfassung", "betriebsverfassungsrecht"),
        ("betriebsverfassungsgesetz", "betriebsverfassungsrecht"),
        ("betriebsverfassungsrechtlich", "betriebsverfassungsrecht"),
        ("betrvg", "betriebsverfassungsrecht"),
        ("works constitution act", "betriebsverfassungsrecht"),
        ("co-determination", "mitbestimmung"),
        ("codetermination", "mitbestimmung"),
        ("collective bargaining", "tarifverhandlung"),
        ("collective agreement", "tarifvertrag"),
        ("collective labour agreement", "tarifvertrag"),
        ("social plan", "sozialplan"),
        ("reconciliation interests", "interessenausgleich"),
        ("workforce reduction", "personalabbau"),
        ("headcount reduction", "personalabbau"),
        ("downsizing", "personalabbau"),
        ("stellenabbau", "personalabbau"),
        ("personalanpassung", "personalabbau"),
        ("613a", "betriebsubergang"),
        // HR controlling, planning and systems.
        ("hr controlling", "personalcontrolling"),
        ("hr analytics", "people-analytics"),
        ("people analytics", "people-analytics"),
        ("workforce analytics", "people-analytics"),
        ("workforce planning", "personalplanung"),
        ("personnel planning", "personalplanung"),
        ("headcount planning", "personalplanung"),
        ("personalbedarfsplanung", "personalplanung"),
        ("human capital management", "hcm"),
        ("hr information system", "hris"),
        ("hr-it-systeme", "hris"),
        ("hr software", "hris"),
        ("personalinformationssystem", "hris"),
        ("success factors", "successfactors"),
    ],
};

#[cfg(test)]
mod tests {
    use super::super::testing::{assert_apart, assert_same, vocab};
    use crate::matching::atoms::{Vocab, is_generic};

    fn hr() -> Vocab {
        let v = vocab(&["Personalleitung", "Arbeitsrecht", "Recruiting"]);
        assert_eq!(v.packs(), ["hr"]);
        v
    }

    #[test]
    fn paraphrases() {
        assert_same(
            &hr(),
            &[
                ("Head of HR", "Personalleitung"),
                ("Personalleiterin", "Leiter Personal"),
                ("HR Director", "HR-Direktorin"),
                ("Chief People Officer", "CHRO"),
                ("Arbeitsdirektorin", "Personalvorstand"),
                ("HR Business Partnerin", "HRBP"),
                ("Talent Acquisition", "Recruiting"),
                ("Personalbeschaffung", "Recruitment"),
                ("Compensation & Benefits", "Vergütungsmanagement"),
                ("Vergütungssysteme", "Total Rewards"),
                ("Payroll", "Lohn- und Gehaltsabrechnung"),
                ("Employment law", "Arbeitsrecht"),
                ("arbeitsrechtliche Kenntnisse", "Arbeitsrecht"),
                ("Works council", "Betriebsrat"),
                ("BetrVG", "Betriebsverfassungsgesetz"),
                ("Co-Determination", "Mitbestimmung"),
                ("Collective bargaining", "Tarifverhandlungen"),
                ("Leadership Development", "Führungskräfteentwicklung"),
                ("Succession planning", "Nachfolgeplanung"),
                ("Workforce planning", "Personalplanung"),
                ("Organisational Development", "Organisationsentwicklung"),
                ("HR-Transformation", "HR Transformation"),
                ("Human Resources", "HR"),
                ("Stellenabbau", "Personalabbau"),
            ],
        );
    }

    #[test]
    fn false_friends_stay_apart() {
        assert_apart(
            &hr(),
            &[
                ("Personalverantwortung", "Personalleitung"),
                ("Personaldienstleister", "Personalleitung"),
                ("Strategic Sourcing", "Active Sourcing"),
                ("Tarifmodelle", "Tarifverhandlungen"),
                ("Organisationstalent", "Talent Management"),
                ("HR-Controlling", "HR"),
                ("Personalentwicklung", "Personal"),
            ],
        );
    }

    /// Broad companion words never count alone; the field name `HR` heads job titles and
    /// stays a word of its own.
    #[test]
    fn broad_words_are_generic() {
        for word in ["personal", "people", "peopl"] {
            assert!(is_generic(word), "{word}");
        }
        assert!(!is_generic("hr"));
        assert!(!is_generic("personalleitung"));
    }
}
