//! Operations and engineering: production and plant management, lean, Six Sigma and
//! operational excellence, maintenance, production planning, quality management
//! (ISO 9001, IATF 16949), automotive, R&D and occupational safety.
//!
//! external contract - do not translate.

use super::Domain;

pub(crate) const DOMAIN: Domain = Domain {
    name: "operations",
    triggers: &[
        "apqp",
        "betriebsleit",
        "excellence",
        "fertigungsleit",
        "fertigungsplan",
        "fertigungssteuer",
        "iatf",
        "instandhalt",
        "instandsetz",
        "kaizen",
        "kvp",
        "lean",
        "oee",
        "ppap",
        "produktionsleit",
        "produktionsplan",
        "produktionssteuer",
        "shop-floor",
        "shopfloor",
        "sigma",
        "smed",
        "tpm",
        "vda",
        "werksleit",
        "wertstrom",
    ],
    generic: &["operation", "technik"],
    concepts: &[
        // Production and plant leadership.
        ("production", "produktion"),
        ("manufacturing", "produktion"),
        ("fertigung", "produktion"),
        ("herstellung", "produktion"),
        ("produktionsleiter", "produktionsleitung"),
        ("produktionsleiterin", "produktionsleitung"),
        ("leiter produktion", "produktionsleitung"),
        ("leiterin produktion", "produktionsleitung"),
        ("leitung produktion", "produktionsleitung"),
        ("head production", "produktionsleitung"),
        ("head manufacturing", "produktionsleitung"),
        ("production manager", "produktionsleitung"),
        ("manufacturing manager", "produktionsleitung"),
        ("fertigungsleiter", "produktionsleitung"),
        ("fertigungsleiterin", "produktionsleitung"),
        ("fertigungsleitung", "produktionsleitung"),
        ("werksleiter", "werksleitung"),
        ("werksleiterin", "werksleitung"),
        ("plant manager", "werksleitung"),
        ("plant director", "werksleitung"),
        ("head plant", "werksleitung"),
        ("standortleiter", "werksleitung"),
        ("standortleiterin", "werksleitung"),
        ("standortleitung", "werksleitung"),
        ("betriebsleiter", "werksleitung"),
        ("betriebsleiterin", "werksleitung"),
        ("betriebsleitung", "werksleitung"),
        ("technischer leiter", "technischeleitung"),
        ("technische leiterin", "technischeleitung"),
        ("technische leitung", "technischeleitung"),
        ("leiter technik", "technischeleitung"),
        ("leiterin technik", "technischeleitung"),
        ("leitung technik", "technischeleitung"),
        ("chief operating officer", "coo"),
        ("head operations", "operationsleitung"),
        ("director operations", "operationsleitung"),
        ("operations director", "operationsleitung"),
        ("operations manager", "operationsleitung"),
        ("leiter operations", "operationsleitung"),
        ("leiterin operations", "operationsleitung"),
        ("leitung operations", "operationsleitung"),
        // Lean, Six Sigma and operational excellence (`Lean Six Sigma` gives both).
        ("lean", "lean-management"),
        ("lean management", "lean-management"),
        ("lean production", "lean-management"),
        ("lean manufacturing", "lean-management"),
        ("lean methoden", "lean-management"),
        ("lean methodik", "lean-management"),
        ("lean prinzipien", "lean-management"),
        ("lean principles", "lean-management"),
        ("six sigma", "six-sigma"),
        ("sigma", "six-sigma"),
        ("operational excellence", "operationalexcellence"),
        ("operative exzellenz", "operationalexcellence"),
        ("kontinuierlicher verbesserungsprozess", "kvp"),
        ("continuous improvement", "kvp"),
        ("continuous improvement process", "kvp"),
        ("kaizen", "kvp"),
        ("shopfloor management", "shopfloor-management"),
        ("shop floor management", "shopfloor-management"),
        ("total productive maintenance", "tpm"),
        ("overall equipment effectiveness", "oee"),
        ("gesamtanlageneffektivitat", "oee"),
        ("single minute exchange", "smed"),
        ("rustzeitoptimierung", "smed"),
        ("rustzeitreduzierung", "smed"),
        ("value stream mapping", "wertstromanalyse"),
        ("value stream design", "wertstromanalyse"),
        ("wertstromdesign", "wertstromanalyse"),
        ("wertstrommethode", "wertstromanalyse"),
        ("process optimisation", "prozessoptimierung"),
        ("process optimization", "prozessoptimierung"),
        // Maintenance.
        ("maintenance", "instandhaltung"),
        ("maintenance management", "instandhaltung"),
        ("instandhaltungsmanagement", "instandhaltung"),
        ("instandsetzung", "instandhaltung"),
        ("wartung", "instandhaltung"),
        ("predictive maintenance", "predictive-maintenance"),
        ("vorausschauende instandhaltung", "predictive-maintenance"),
        ("instandhaltungsleiter", "instandhaltungsleitung"),
        ("instandhaltungsleiterin", "instandhaltungsleitung"),
        ("leiter instandhaltung", "instandhaltungsleitung"),
        ("leiterin instandhaltung", "instandhaltungsleitung"),
        ("leitung instandhaltung", "instandhaltungsleitung"),
        ("maintenance manager", "instandhaltungsleitung"),
        ("head maintenance", "instandhaltungsleitung"),
        // Production planning.
        ("production planning", "produktionsplanung"),
        ("fertigungsplanung", "produktionsplanung"),
        ("produktionsplanung steuerung", "pps"),
        ("production planning control", "pps"),
        ("fertigungssteuerung", "produktionssteuerung"),
        ("production control", "produktionssteuerung"),
        // Quality management (the same keys and concepts as in `pharma`).
        ("quality assurance", "qualitatssicherung"),
        ("qa", "qualitatssicherung"),
        ("quality control", "qualitatskontrolle"),
        ("quality management", "qualitatsmanagement"),
        ("qm", "qualitatsmanagement"),
        ("quality manager", "qualitatsmanagement"),
        ("qualitatsmanager", "qualitatsmanagement"),
        ("qualitatsmanagerin", "qualitatsmanagement"),
        ("quality management system", "qualitatsmanagementsystem"),
        ("qms", "qualitatsmanagementsystem"),
        ("qm system", "qualitatsmanagementsystem"),
        ("head quality", "qualitatsleitung"),
        ("quality director", "qualitatsleitung"),
        ("director quality", "qualitatsleitung"),
        ("qualitatsleiter", "qualitatsleitung"),
        ("qualitatsleiterin", "qualitatsleitung"),
        ("leiter qualitatssicherung", "qualitatsleitung"),
        ("leiterin qualitatssicherung", "qualitatsleitung"),
        ("leitung qualitatssicherung", "qualitatsleitung"),
        ("failure mode effects analysis", "fmea"),
        ("statistical process control", "spc"),
        ("statistische prozesslenkung", "spc"),
        ("complaint management", "reklamationsmanagement"),
        ("reklamationsbearbeitung", "reklamationsmanagement"),
        // Automotive.
        ("automotive industry", "automotive"),
        ("automobilindustrie", "automotive"),
        ("automobilbranche", "automotive"),
        ("automotive branche", "automotive"),
        ("fahrzeugbau", "automotive"),
        ("automobil", "automotive"),
        ("automotive supplier", "automotive-zulieferer"),
        ("automobilzulieferer", "automotive-zulieferer"),
        ("automobilzulieferindustrie", "automotive-zulieferer"),
        // Engineering, R&D and safety.
        ("industrial engineering", "industrial-engineering"),
        ("research development", "forschung-entwicklung"),
        ("forschung entwicklung", "forschung-entwicklung"),
        ("f&e", "forschung-entwicklung"),
        ("r&d", "forschung-entwicklung"),
        ("design engineering", "konstruktion"),
        ("occupational safety", "arbeitssicherheit"),
        ("occupational health safety", "arbeitssicherheit"),
        ("health safety environment", "arbeitssicherheit"),
        ("hse", "arbeitssicherheit"),
        ("ehs", "arbeitssicherheit"),
        ("arbeitsschutz", "arbeitssicherheit"),
    ],
};

#[cfg(test)]
mod tests {
    use super::super::testing::{assert_apart, assert_same, vocab};
    use crate::matching::atoms::{Vocab, atoms};

    fn operations() -> Vocab {
        let v = vocab(&["Lean Management", "Werksleitung", "Instandhaltung"]);
        assert_eq!(v.packs(), ["operations"]);
        v
    }

    #[test]
    fn paraphrases() {
        assert_same(
            &operations(),
            &[
                ("Production", "Produktion"),
                ("Manufacturing", "Fertigung"),
                ("Produktionsleiterin", "Head of Production"),
                ("Plant Manager", "Werksleiter"),
                ("Standortleiterin", "Werksleitung"),
                ("Technischer Leiter", "Leitung Technik"),
                ("Lean", "Lean Management"),
                ("Lean Production", "Lean-Methoden"),
                ("Six Sigma", "Six-Sigma"),
                ("Operational Excellence", "Operative Exzellenz"),
                ("KVP", "Kontinuierlicher Verbesserungsprozess"),
                ("Kaizen", "Continuous Improvement"),
                ("Shop Floor Management", "Shopfloor-Management"),
                ("Total Productive Maintenance", "TPM"),
                ("Value Stream Mapping", "Wertstromanalyse"),
                ("Maintenance", "Instandhaltung"),
                ("Wartung und Instandsetzung", "Instandhaltung"),
                ("Production planning", "Produktionsplanung"),
                ("Produktionsplanung und -steuerung", "PPS"),
                ("Quality Management", "Qualitätsmanagement"),
                ("QM", "Quality Management"),
                ("FMEA", "Failure Mode and Effects Analysis"),
                ("Automobilindustrie", "Automotive"),
                ("Automotive supplier", "Automobilzulieferer"),
                ("F&E", "Research & Development"),
                ("Arbeitsschutz", "HSE"),
            ],
        );
        let lss = atoms("Lean Six Sigma", &operations());
        assert_eq!(lss, ["lean-management", "six-sigma"]);
    }

    #[test]
    fn false_friends_stay_apart() {
        assert_apart(
            &operations(),
            &[
                ("LeanIX", "Lean"),
                ("Lean", "LeanIX"),
                ("Operational Excellence", "Excel"),
                ("Produktionscontrolling", "Produktion"),
                ("Unternehmensplanung", "Produktionsplanung"),
                ("technisches Verständnis", "Technischer Leiter"),
                ("OEM", "OEE"),
            ],
        );
    }
}
