//! Procurement and supply chain: strategic and operational purchasing, suppliers,
//! contracts and negotiation, planning (S&OP, demand, MRP), inventory and logistics.
//!
//! external contract - do not translate.

use super::Domain;

pub(crate) const DOMAIN: Domain = Domain {
    name: "procurement",
    triggers: &[
        "ariba",
        "bedarfsplan",
        "beschaffung",
        "category",
        "coupa",
        "demand",
        "disposition",
        "einkauf",
        "intralogistik",
        "inventory",
        "jaggaer",
        "lagerhalt",
        "lagerlogistik",
        "lagerwirtschaft",
        "lieferantenbewert",
        "lieferantenentwickl",
        "lieferantenmanag",
        "logistics",
        "logistikleit",
        "logistikmanag",
        "logistikplan",
        "materialdispo",
        "materialwirtschaft",
        "p2p",
        "procure",
        "purchas",
        "rahmenvertr",
        "s&op",
        "source-to-pay",
        "sourcing",
        "spend",
        "supply",
        "transportlogistik",
        "warengruppe",
    ],
    generic: &["lieferant", "supplier", "supply"],
    concepts: &[
        // The field and its roles.
        ("procurement", "einkauf"),
        ("purchasing", "einkauf"),
        ("beschaffung", "einkauf"),
        ("einkaufsmanagement", "einkauf"),
        ("beschaffungsmanagement", "einkauf"),
        ("procurement management", "einkauf"),
        ("einkauferin", "einkauf"),
        ("buyer", "einkauf"),
        ("einkaufsleiter", "einkaufsleitung"),
        ("einkaufsleiterin", "einkaufsleitung"),
        ("leiter einkauf", "einkaufsleitung"),
        ("leiterin einkauf", "einkaufsleitung"),
        ("leitung einkauf", "einkaufsleitung"),
        ("head procurement", "einkaufsleitung"),
        ("head purchasing", "einkaufsleitung"),
        ("procurement director", "einkaufsleitung"),
        ("director procurement", "einkaufsleitung"),
        ("purchasing director", "einkaufsleitung"),
        ("director purchasing", "einkaufsleitung"),
        ("chief procurement officer", "einkaufsleitung"),
        ("cpo", "einkaufsleitung"),
        ("einkaufsdirektor", "einkaufsleitung"),
        ("einkaufsdirektorin", "einkaufsleitung"),
        // Strategic and operational purchasing.
        ("strategic procurement", "strategischereinkauf"),
        ("strategic purchasing", "strategischereinkauf"),
        ("strategic sourcing", "strategischereinkauf"),
        ("strategischer einkauf", "strategischereinkauf"),
        ("strategische beschaffung", "strategischereinkauf"),
        ("sourcing strategy", "strategischereinkauf"),
        ("procurement strategy", "strategischereinkauf"),
        ("einkaufsstrategie", "strategischereinkauf"),
        ("beschaffungsstrategie", "strategischereinkauf"),
        ("operational procurement", "operativereinkauf"),
        ("operational purchasing", "operativereinkauf"),
        ("operativer einkauf", "operativereinkauf"),
        ("operative beschaffung", "operativereinkauf"),
        // A recruiting method, not sourcing in purchasing.
        ("active sourcing", "direktansprache"),
        ("category management", "warengruppenmanagement"),
        ("category manager", "warengruppenmanagement"),
        ("category strategy", "warengruppenmanagement"),
        ("commodity management", "warengruppenmanagement"),
        ("commodity manager", "warengruppenmanagement"),
        ("warengruppenmanager", "warengruppenmanagement"),
        ("warengruppenmanagerin", "warengruppenmanagement"),
        ("warengruppenstrategie", "warengruppenmanagement"),
        ("warengruppenverantwortung", "warengruppenmanagement"),
        ("spend analysis", "spend-analyse"),
        ("spend analytics", "spend-analyse"),
        ("ausgabenanalyse", "spend-analyse"),
        ("cost reduction", "kostensenkung"),
        ("cost savings", "kostensenkung"),
        ("savings", "kostensenkung"),
        ("einsparung", "kostensenkung"),
        ("kostenreduktion", "kostensenkung"),
        ("kostenreduzierung", "kostensenkung"),
        ("kosteneinsparung", "kostensenkung"),
        // Suppliers.
        ("supplier management", "lieferantenmanagement"),
        ("vendor management", "lieferantenmanagement"),
        ("lieferanten management", "lieferantenmanagement"),
        ("supplier relationship management", "lieferantenmanagement"),
        ("srm", "lieferantenmanagement"),
        ("lieferantenbeziehungsmanagement", "lieferantenmanagement"),
        ("supplier development", "lieferantenentwicklung"),
        ("supplier evaluation", "lieferantenbewertung"),
        ("supplier assessment", "lieferantenbewertung"),
        ("supplier rating", "lieferantenbewertung"),
        ("supplier qualification", "lieferantenqualifizierung"),
        ("supplier selection", "lieferantenauswahl"),
        ("supplier audit", "lieferantenaudit"),
        ("supplier quality", "lieferantenqualitat"),
        ("supplier risk management", "lieferantenrisikomanagement"),
        // Contracts, negotiation and tenders.
        ("framework agreement", "rahmenvertrag"),
        ("framework contract", "rahmenvertrag"),
        ("rahmenvereinbarung", "rahmenvertrag"),
        ("negotiation", "verhandlung"),
        ("verhandlungsfuhrung", "verhandlung"),
        ("contract negotiation", "vertragsverhandlung"),
        ("price negotiation", "preisverhandlung"),
        ("contract management", "vertragsmanagement"),
        ("tender", "ausschreibung"),
        ("rfq", "ausschreibung"),
        ("rfp", "ausschreibung"),
        ("request quotation", "ausschreibung"),
        ("request proposal", "ausschreibung"),
        ("public procurement", "offentlichevergabe"),
        ("offentliche vergabe", "offentlichevergabe"),
        ("offentliche auftragsvergabe", "offentlichevergabe"),
        ("freight tender", "logistikausschreibung"),
        ("logistics tender", "logistikausschreibung"),
        ("transport tender", "logistikausschreibung"),
        ("frachtausschreibung", "logistikausschreibung"),
        ("transportausschreibung", "logistikausschreibung"),
        // Procure-to-pay (`to` is too short to stay in the text).
        ("procure pay", "procure-to-pay"),
        ("purchase pay", "procure-to-pay"),
        ("purchase-to-pay", "procure-to-pay"),
        ("p2p", "procure-to-pay"),
        ("source pay", "source-to-pay"),
        ("s2p", "source-to-pay"),
        ("purchase order", "bestellung"),
        ("purchase requisition", "bestellanforderung"),
        ("banf", "bestellanforderung"),
        // Supply chain planning and inventory.
        ("supply chain", "supply-chain"),
        ("supply chain management", "supply-chain"),
        ("scm", "supply-chain"),
        ("lieferkette", "supply-chain"),
        ("lieferkettenmanagement", "supply-chain"),
        ("sales operations planning", "s&op"),
        ("absatz produktionsplanung", "s&op"),
        ("integrated business planning", "s&op"),
        ("demand planning", "bedarfsplanung"),
        ("demand forecasting", "bedarfsplanung"),
        ("bedarfsprognose", "bedarfsplanung"),
        ("supply planning", "supply-planning"),
        ("materialdisposition", "disposition"),
        ("disponent", "disposition"),
        ("disponentin", "disposition"),
        ("mrp", "disposition"),
        ("material planning", "disposition"),
        ("materialbedarfsplanung", "disposition"),
        ("inventory management", "bestandsmanagement"),
        ("inventory optimisation", "bestandsmanagement"),
        ("inventory optimization", "bestandsmanagement"),
        ("bestandsoptimierung", "bestandsmanagement"),
        ("lagerbestandsmanagement", "bestandsmanagement"),
        ("safety stock", "sicherheitsbestand"),
        ("materials management", "materialwirtschaft"),
        ("materialmanagement", "materialwirtschaft"),
        // Logistics, customs and trade.
        ("logistics", "logistik"),
        ("logistikerin", "logistik"),
        ("warehouse management", "lagerlogistik"),
        ("warehouse logistics", "lagerlogistik"),
        ("warehouse operations", "lagerlogistik"),
        ("lagerwirtschaft", "lagerlogistik"),
        ("lagerverwaltung", "lagerlogistik"),
        ("lagerhaltung", "lagerlogistik"),
        ("transport management", "transportmanagement"),
        ("customs clearance", "zollabwicklung"),
        ("foreign trade", "aussenhandel"),
        ("lksg", "lieferkettengesetz"),
        ("supply chain act", "lieferkettengesetz"),
        ("lieferkettensorgfaltspflichtengesetz", "lieferkettengesetz"),
        // False friends: other things that start or end like purchasing words.
        ("purchase price allocation", "kaufpreisallokation"),
        ("share purchase agreement", "unternehmenskaufvertrag"),
        ("supply chain finance", "lieferkettenfinanzierung"),
        ("einkaufszentrum", "shopping-center"),
        ("einkaufsmoglichkeit", "shopping"),
        ("einkaufsgutschein", "gutschein"),
        ("dispositionskredit", "kontokorrentkredit"),
        ("data warehouse", "data-warehouse"),
    ],
};

#[cfg(test)]
mod tests {
    use super::super::testing::{assert_apart, assert_same, vocab};
    use crate::matching::atoms::Vocab;

    fn procurement() -> Vocab {
        let v = vocab(&["Strategischer Einkauf", "Lieferantenmanagement", "S&OP"]);
        assert_eq!(v.packs(), ["procurement"]);
        v
    }

    #[test]
    fn paraphrases() {
        assert_same(
            &procurement(),
            &[
                ("Procurement", "Einkauf"),
                ("Purchasing", "Beschaffung"),
                ("Einkäuferin", "Einkauf"),
                ("Head of Procurement", "Einkaufsleiter"),
                ("CPO", "Leiterin Einkauf"),
                ("Strategic Sourcing", "Strategischer Einkauf"),
                ("Sourcing strategy", "Einkaufsstrategie"),
                ("Operativer Einkauf", "Operational Procurement"),
                ("Category Management", "Warengruppenmanagement"),
                ("Category Manager", "Warengruppenstrategie"),
                ("Supplier Management", "Lieferantenmanagement"),
                ("Lieferanten-Management", "Supplier Relationship Management"),
                ("Framework agreements", "Rahmenverträge"),
                ("Negotiation", "Verhandlung"),
                ("Contract negotiations", "Vertragsverhandlungen"),
                ("Sales & Operations Planning", "S&OP"),
                ("Absatz- und Produktionsplanung", "S&OP"),
                ("Demand Planning", "Bedarfsplanung"),
                ("Materialdisposition", "MRP"),
                ("Inventory Management", "Bestandsoptimierung"),
                ("Supply Chain Management", "Lieferkette"),
                ("Logistics", "Logistik"),
                ("Warehouse Management", "Lagerhaltung"),
                ("P2P", "Procure-to-Pay"),
                ("Procure to Pay", "Procure-to-Pay"),
                ("Cost reduction", "Kostensenkung"),
                ("Tender", "Ausschreibungen"),
            ],
        );
    }

    #[test]
    fn false_friends_stay_apart() {
        assert_apart(
            &procurement(),
            &[
                ("Einkaufszentrum", "Einkauf"),
                ("Einkaufsmöglichkeiten in der Nähe", "Einkauf"),
                ("Purchase Price Allocation", "Purchasing"),
                ("Active Sourcing", "Strategic Sourcing"),
                ("Dispositionskredit", "Disposition"),
                ("Supply Chain Finance", "Supply Chain"),
                ("Data Warehouse", "Warehouse Management"),
                ("Strategische Planung", "Strategischer Einkauf"),
                ("Lagebericht", "Lagerhaltung"),
            ],
        );
    }
}
