// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stage of a job in the user's pipeline (set by the user, never by a run): saved
 * ("Gemerkt", the star) comes first, then the application.
 */
export type AppStatus = "saved" | "applied" | "interview" | "offer" | "rejected";
