// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobCounts } from "./JobCounts";
import type { Mailbox } from "./Mailbox";
import type { Platform } from "./Platform";
import type { PortalState } from "./PortalState";
import type { ProfileInfo } from "./ProfileInfo";
import type { ResetSummary } from "./ResetSummary";
import type { RunSnapshot } from "./RunSnapshot";
import type { RunSummary } from "./RunSummary";
import type { SettingsView } from "./SettingsView";

/**
 * Everything the interface needs at the start (and after a reload).
 */
export type AppState = { platform: Platform, dryRun: boolean, 
/**
 * No run has finished yet and no job is known.
 */
firstRun: boolean, 
/**
 * The run in progress (after a reload the interface picks up from here).
 */
running: RunSnapshot | null, settings: SettingsView, mailbox: Mailbox, profile: ProfileInfo | null, portals: Array<PortalState>, autoFetchOnStart: boolean, 
/**
 * Days after which old jobs without a stage archive themselves; 0 = never.
 */
autoArchiveDays: number, 
/**
 * The last fetch (fetch or whole mailbox) - a rescore or a details run is none.
 */
lastRun: RunSummary | null, counts: JobCounts, matchPending: number, dataDir: string, logDir: string, resetReport: ResetSummary | null, };
