// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the user's application for a job stands (set by the user, never by a run).
 */
export type AppStatus = "applied" | "interview" | "offer" | "rejected";
