// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user's mark on a job (set by the user, never by a run, with the time it was set):
 * saved ("Gemerkt", the star) or sent ("Beworben": the user applied).
 */
export type AppStatus = "saved" | "sent";
