// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of "delete text files".
 */
export type ClearedTxt = { removed: number, 
/**
 * File names that could not be deleted (open right now).
 */
failed: Array<string>, };
