// Generated by core/tests/contract.rs from the command table in src-tauri/src/commands/mod.rs. Do not edit.
import type { Channel } from "@tauri-apps/api/core";
import type { AppState } from "./AppState";
import type { ClearedTxt } from "./ClearedTxt";
import type { ExportSummary } from "./ExportSummary";
import type { JobDetail } from "./JobDetail";
import type { JobKey } from "./JobKey";
import type { JobPage } from "./JobPage";
import type { JobQuery } from "./JobQuery";
import type { Mailbox } from "./Mailbox";
import type { OpenTarget } from "./OpenTarget";
import type { Portal } from "./Portal";
import type { ProfileInfo } from "./ProfileInfo";
import type { RunEvent } from "./RunEvent";
import type { RunRequest } from "./RunRequest";
import type { SettingsPatch } from "./SettingsPatch";

/** Every IPC command: its arguments and its result. */
export type Commands = {
  app_state: { args: { channel: Channel<RunEvent> }; result: AppState };
  start_run: { args: { request: RunRequest; channel: Channel<RunEvent> }; result: null };
  cancel_run: { args: Record<string, never>; result: null };
  list_jobs: { args: { query: JobQuery }; result: JobPage };
  job_detail: { args: { key: JobKey }; result: JobDetail };
  mark_read: { args: { key: JobKey }; result: boolean };
  set_pinned: { args: { key: JobKey; on: boolean }; result: boolean };
  pick_profile: { args: Record<string, never>; result: ProfileInfo | null };
  remove_profile: { args: Record<string, never>; result: boolean };
  save_profile_template: { args: Record<string, never>; result: string | null };
  save_mailbox: { args: { user: string; password: string }; result: Mailbox };
  remove_mailbox: { args: Record<string, never>; result: boolean };
  portal_login: { args: { portal: Portal }; result: boolean };
  portal_logout: { args: { portal: Portal }; result: boolean };
  pick_workspace: { args: Record<string, never>; result: string | null };
  rewrite_txt: { args: Record<string, never>; result: ExportSummary };
  clear_txt: { args: Record<string, never>; result: ClearedTxt };
  open_target: { args: { target: OpenTarget }; result: null };
  save_settings: { args: { patch: SettingsPatch }; result: AppState };
  reset_all: { args: Record<string, never>; result: null };
  report_ui_error: { args: { message: string; source: string | null; line: number | null }; result: null };
};
