// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";

/**
 * Result of a permanent delete of jobs.
 */
export type Deleted = { 
/**
 * Jobs deleted (with the duplicates that stood for them).
 */
count: number, 
/**
 * The overview could not be written again (e.g. open in Excel); `params.target` names
 * what failed. The jobs are deleted anyway.
 */
exportError: ErrorInfo | null, };
