// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";
import type { JobKey } from "./JobKey";

/**
 * Result of a permanent delete of jobs.
 */
export type Deleted = { 
/**
 * Jobs deleted, as the list showed them: one per row (a duplicate that stood behind a
 * row went with it but does not count).
 */
count: number, 
/**
 * The keys of every row that went, duplicates included: the page drops them from lists,
 * the reader and pending undos.
 */
keys: Array<JobKey>, 
/**
 * The overview could not be written again (e.g. open in Excel); `params.target` names
 * what failed. The jobs are deleted anyway.
 */
exportError: ErrorInfo | null, };
