// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the job details.
 */
export type DetailState = { "kind": "ok" } | { "kind": "pending", retryAt: string | null, } | { "kind": "teaser" } | { "kind": "failed", attempts: number, retryAt: string | null, } | { "kind": "gone" } | { "kind": "unfetchable" };
