// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * An alert mail of a run without recognised jobs.
 */
export type EmptyAlert = { portal: Portal, subject: string, date: string | null, 
/**
 * Gmail message id (hexadecimal) - opened through `open_target`.
 */
gmailId: string | null, };
