// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable error codes for the interface (it reacts to these, never to a text).
 */
export type ErrorKind = "db" | "fileLocked" | "io" | "xlsx" | "corrupt" | "newerSchema" | "invalid" | "busy" | "notFound" | "dryRun" | "mailMissing" | "mailConnect" | "mailAuth" | "mailTimeout" | "mailLost" | "mailNotGmail" | "mailServer" | "mailCancelled" | "secretStore" | "secretCorrupt" | "portalUnavailable" | "portalPaused" | "portalQuota" | "internal";
