// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorKind } from "./ErrorKind";

/**
 * An error as the interface sees it: a code plus data (paths, numbers, portal keys).
 */
export type ErrorInfo = { kind: ErrorKind, params: Record<string, string | number | boolean | null>, };
