// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the profile backs a reason.
 */
export type Evidence = { 
/**
 * The profile phrase.
 */
profile: string, 
/**
 * JSON path in the profile file.
 */
path: string, 
/**
 * Code of the match ladder step (exact, stem, synonym ...).
 */
via: string, 
/**
 * Words of the ad.
 */
quote: string, };
