// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";

export type ExportSummary = { 
/**
 * Written Excel overview (if written in this run).
 */
overviewXlsx: string | null, 
/**
 * Written HTML overview (if written in this run).
 */
overviewHtml: string | null, 
/**
 * A foreign overview at the same path was backed up here.
 */
backup: string | null, txtWritten: number, 
/**
 * Number of text files that could not be written - the number for every display.
 */
txtFailed: number, 
/**
 * The first error (closest to the cause); `params.target` names what failed.
 */
error: ErrorInfo | null, };
