// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasonKind } from "./ReasonKind";

/**
 * A highlighted passage of the full text.
 */
export type Highlight = { id: string, 
/**
 * UTF-16 offsets.
 */
start: number, end: number, kind: ReasonKind, 
/**
 * Id of the reason it belongs to.
 */
reason: string, };
