// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * Why an input was refused - a code with data, never a sentence.
 */
export type InvalidInput = { "reason": "noPortal" } | { "reason": "profileNotUtf8" } | { "reason": "profileNotJson", line: number, column: number, } | { "reason": "profileNotObject", found: string, } | { "reason": "profileValue", field: string, row: number | null, } | { "reason": "profileAnswer" } | { "reason": "mailAddress" } | { "reason": "appPassword" } | { "reason": "noSignIn", portal: Portal, };
