// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalNew } from "./PortalNew";

/**
 * Counts of the list (with the search applied, whatever the facet). Every number of the
 * page comes from here: the facets, the tiles, the sidebar and the new jobs per portal.
 */
export type JobCounts = { 
/**
 * Unread and not excluded ("Neu").
 */
new: number, all: number, excluded: number, 
/**
 * Scored in the high band.
 */
high: number, 
/**
 * Without a full text.
 */
noDetail: number, 
/**
 * Pinned ("Merken").
 */
pinned: number, 
/**
 * With an application status.
 */
applications: number, 
/**
 * Hidden - the only count a hidden job is in.
 */
hidden: number, 
/**
 * `new` per portal: every portal, in the order of `Portal::ALL`.
 */
newByPortal: Array<PortalNew>, };
