// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalNew } from "./PortalNew";

/**
 * Counts of the list (with the search applied, whatever the place and the filter), from
 * the same statement as the page. Every number of the page comes from here: the places, the
 * list's filter segments, the tiles and the unread jobs per portal.
 */
export type JobCounts = { 
/**
 * In the inbox ("Eingang").
 */
inbox: number, 
/**
 * Unread in the inbox, not excluded.
 */
unread: number, 
/**
 * Favourites (the star), in the inbox or the archive.
 */
favourites: number, archive: number, 
/**
 * In the trash ("Papierkorb").
 */
trash: number, 
/**
 * Excluded, in the inbox.
 */
excluded: number, 
/**
 * Scored in the high band, in the inbox.
 */
high: number, 
/**
 * Without a full text, in the inbox.
 */
noDetail: number, 
/**
 * `unread` per portal: every portal, in the order of `Portal::ALL`.
 */
newByPortal: Array<PortalNew>, };
