// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of the list (with the search applied, whatever the facet).
 */
export type JobCounts = { new: number, all: number, excluded: number, high: number, noDetail: number, };
