// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * Identity of a job across all mails and runs.
 */
export type JobKey = { portal: Portal, id: string, };
