// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The alert mail a job came from.
 */
export type JobMail = { subject: string, gmailUrl: string | null, };
