// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { KeyFacts } from "./KeyFacts";
import type { MatchStatus } from "./MatchStatus";
import type { Notice } from "./Notice";

/**
 * The match of a job in the list.
 */
export type JobMatch = { 
/**
 * 0-100; also kept for excluded jobs.
 */
score: number, band: Band, status: MatchStatus, note: Notice | null, mustMet: number, mustTotal: number, 
/**
 * At most two met requirements, quoted from the ad.
 */
top: Array<string>, 
/**
 * Rate, start, duration, remote share and contract type of the ad.
 */
facts: KeyFacts, };
