// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobCounts } from "./JobCounts";
import type { JobView } from "./JobView";

/**
 * One page of the job list with its counts.
 */
export type JobPage = { jobs: Array<JobView>, counts: JobCounts, };
