// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobFacet } from "./JobFacet";
import type { JobSort } from "./JobSort";

/**
 * Which jobs the list shows.
 */
export type JobQuery = { facet: JobFacet, sort: JobSort, search: string | null, 
/**
 * At most [`MAX_PAGE`]; 0 = counts only.
 */
limit: number, offset: number, };
