// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobSort } from "./JobSort";
import type { Place } from "./Place";

/**
 * Which jobs the list shows: the jobs of one place, optionally only the unread ones.
 */
export type JobQuery = { place: Place, 
/**
 * Only the unread jobs (the excluded ones last, uncounted).
 */
unread: boolean, 
/**
 * The favourites of the inbox and the archive instead of the place (each row keeps its
 * place).
 */
favourites: boolean, 
/**
 * By match, or by date: the alert mail's, in the trash the day the job went there.
 */
sort: JobSort, search: string | null, 
/**
 * At most [`MAX_PAGE`]; 0 = counts only.
 */
limit: number, offset: number, };
