// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobSort } from "./JobSort";
import type { Place } from "./Place";

/**
 * Which jobs the list shows: the jobs of one place, optionally only the unread ones.
 */
export type JobQuery = { place: Place, 
/**
 * Only the unread jobs (the excluded ones last, uncounted).
 */
unread: boolean, 
/**
 * For the inbox; the archive lists the latest archived first, the trash the latest
 * trashed.
 */
sort: JobSort, search: string | null, 
/**
 * At most [`MAX_PAGE`]; 0 = counts only.
 */
limit: number, offset: number, };
