// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppStatus } from "./AppStatus";
import type { DetailState } from "./DetailState";
import type { JobKey } from "./JobKey";
import type { JobMatch } from "./JobMatch";
import type { Portal } from "./Portal";
import type { WorkMode } from "./WorkMode";

/**
 * One row of the job list.
 */
export type JobView = { key: JobKey, portal: Portal, 
/**
 * Empty when neither the mail nor the link carries a usable title.
 */
title: string, company: string, location: string, workMode: WorkMode | null, mailDate: string | null, firstSeenAt: string, unread: boolean, 
/**
 * Saved ("Gemerkt", the star): the stage `saved`.
 */
pinned: boolean, detail: DetailState, 
/**
 * The full text is short (verified, but under 100 characters).
 */
short: boolean, match: JobMatch | null, 
/**
 * The same job was also announced by these portals.
 */
alsoOn: Array<Portal>, 
/**
 * The user's mark (`null` = none; `saved` is the star, `sent` "Beworben").
 */
appStatus: AppStatus | null, 
/**
 * When the mark was set.
 */
statusAt: string | null, 
/**
 * The job is archived (by the user or by age).
 */
archived: boolean, 
/**
 * The user marked the job as fitting although the engine excludes it ("Trotzdem
 * passend"): it counts as scored with its fit score, its note is `userOverride`.
 */
overridden: boolean, };
