// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The key facts of an ad as the engine read them (the page facts first, then the text):
 * numbers and codes for the list row and the reader, `null` when the ad says nothing.
 */
export type KeyFacts = { 
/**
 * Highest rate amount stated, per day or per hour (`hourly`).
 */
rate: number | null, hourly: boolean | null, 
/**
 * Currency code of a rate not in EUR (`CHF`).
 */
currency: string | null, 
/**
 * The ad names a rate to be agreed (`nach Absprache`) without an amount.
 */
rateOpen: boolean | null, 
/**
 * Start: `now`, `vague` or an ISO date (`2026-11-01`).
 */
start: string | null, 
/**
 * Duration in months.
 */
months: number | null, 
/**
 * Remote share in percent, from and to (equal when the ad states one share).
 */
remoteFrom: number | null, remoteTo: number | null, 
/**
 * Contract type: `interim`, `permanent` or `anue` (`null` when unclear).
 */
contract: string | null, };
