// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The app's language. German on a German system, English on any other.
 */
export type Language = "de" | "en";
