// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How well a job fits the profile.
 */
export type MatchStatus = "scored" | "excluded" | "unscorable";
