// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKey } from "./JobKey";
import type { Place } from "./Place";

/**
 * A job an undo takes back to the place it came from (`move_back`).
 */
export type MoveBack = { key: JobKey, to: Place, 
/**
 * When the job went to the trash ([`JobView::trashed_at`]): back in the trash it keeps
 * its date and its days until the trash empties itself.
 */
trashedAt: string | null, };
