// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The jobs a mailbox run brought - the "neue Jobs" of the run card: first seen in the run
 * (a job several portals announce counts once, as its original), excluded ones left out;
 * `high`: how many of them are scored in the high band.
 */
export type NewJobs = { count: number, high: number, };
