// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A statement for the interface as a code with data - the core never sends prose.
 */
export type Notice = { code: string, params: Record<string, string | number | boolean | null>, };
