// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKey } from "./JobKey";
import type { Portal } from "./Portal";

/**
 * What `open_target` may open - never an arbitrary path or link from the page.
 */
export type OpenTarget = { "kind": "jobUrl", key: JobKey, } | { "kind": "gmail", key: JobKey, } | { "kind": "alertMail", gmailId: string, } | { "kind": "portalHome", portal: Portal, } | { "kind": "appPasswordPage" } | { "kind": "twoStepPage" } | { "kind": "workspace" } | { "kind": "excel" } | { "kind": "overview" } | { "kind": "logDir" };
