// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";

export type Outcome = { "kind": "completed" } | { "kind": "cancelled" } | { "kind": "failed", error: ErrorInfo, };
