// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a portal pauses or stopped - a code for the interface.
 */
export type PauseReason = "throttled" | "blocked" | "layoutChanged" | "stateUnreadable" | "network" | "challenged";
