// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a job is, like a mail: in the inbox ("Eingang", the active jobs), the archive or the
 * trash ("Papierkorb"). A job is in exactly one place; the favourite (the star) is a flag of
 * its own. Runs never move a job, except that old ones archive themselves and an old trash
 * empties itself (settings).
 */
export type Place = "inbox" | "archive" | "trash";
