// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";
import type { PortalHealth } from "./PortalHealth";
import type { PortalLogin } from "./PortalLogin";
import type { Quota } from "./Quota";

/**
 * A portal in the settings.
 */
export type PortalState = { portal: Portal, enabled: boolean, fetchDetails: boolean, login: PortalLogin, loginEnabled: boolean, 
/**
 * `null` = unknown (or no sign-in), `false` = sign-in needed.
 */
signedIn: boolean | null, health: PortalHealth, 
/**
 * The user has to act on the health ([`PortalHealth::action_needed`]).
 */
actionNeeded: boolean, quota: Quota | null, };
