// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a portal offers a sign-in.
 */
export type PortalLogin = "none" | "optional";
