// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * The new jobs ("Neu") of one portal.
 */
export type PortalNew = { portal: Portal, new: number, };
