// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

export type PortalPatch = { portal: Portal, enabled: boolean | null, fetchDetails: boolean | null, loginEnabled: boolean | null, };
