// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PauseReason } from "./PauseReason";

/**
 * Health of a portal for the interface: why it rests or what looks wrong.
 */
export type PortalHealth = { "kind": "ok" } | { "kind": "paused", until: string | null, reason: PauseReason, } | { "kind": "quotaReached", until: string, } | { "kind": "layoutSuspect", emptyMails: number, pages: number, } | { "kind": "loginRequired" };
