// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";
import type { PortalHealth } from "./PortalHealth";

/**
 * One portal in the run summary.
 */
export type PortalSummary = { portal: Portal, new: number, known: number, dup: number, 
/**
 * Job details fetched (full text found).
 */
fetched: number, 
/**
 * Pages without a description.
 */
failed: number, 
/**
 * Ads that no longer exist.
 */
gone: number, 
/**
 * Jobs left for later (pause, cap, sign-in, breaker, network).
 */
skipped: number, 
/**
 * Why the portal stopped in this run.
 */
stopped: PortalHealth | null, };
