// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Portal } from "./Portal";

/**
 * The unread jobs of one portal (in the inbox, not excluded).
 */
export type PortalNew = { portal: Portal, new: number, };
