// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notice } from "./Notice";

/**
 * "What the app understood" of the profile.
 */
export type ProfileUnderstanding = { competenceCount: number, competences: Array<string>, sources: Array<string>, criteria: Array<Notice>, warnings: Array<Notice>, };
