// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One core competence.
 */
export type ProfileCompetence = { name: string, years: number | null, 
/**
 * Other words for the same competence (`auch`).
 */
aliases: Array<string>, 
/**
 * Index of the entry in the JSON the form was read from; `null` for a new one.
 */
origin: number | null, };
