// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileForm } from "./ProfileForm";

/**
 * Saving the editor: the form as it was handed out (`before`) and as the user left it;
 * only what differs is written. `source` is the JSON of a draft (`{}` for a new profile),
 * `null` for the stored profile.
 */
export type ProfileSave = { before: ProfileForm, after: ProfileForm, source: string | null, };
