// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileCompetence } from "./ProfileCompetence";
import type { ProfileCriteria } from "./ProfileCriteria";
import type { ProfileLanguage } from "./ProfileLanguage";
import type { ProfileWishes } from "./ProfileWishes";

/**
 * The editable profile.
 */
export type ProfileForm = { 
/**
 * `name` (the skill names the consultant with it; the engine never reads it).
 */
name: string, 
/**
 * `titel`, the professional role.
 */
title: string, 
/**
 * `kernkompetenzen[]` with `kompetenz`, `jahre` and `auch`.
 */
competences: Array<ProfileCompetence>, 
/**
 * `alleinstellungsmerkmale[]`.
 */
strengths: Array<string>, 
/**
 * `keywords[]`.
 */
keywords: Array<string>, 
/**
 * `berufserfahrung_jahre`.
 */
years: number | null, 
/**
 * `abschluss` and `ausbildung[].abschluss`.
 */
degrees: Array<string>, 
/**
 * `branchen[].branche`.
 */
industries: Array<string>, 
/**
 * `methoden_tools[].name`.
 */
tools: Array<string>, 
/**
 * `zertifizierungen[].name`.
 */
certificates: Array<string>, 
/**
 * `sprachen[]` with `sprache` and `niveau` (`languages[]` with `language` and `level`).
 */
languages: Array<ProfileLanguage>, 
/**
 * `schwerpunkte[]` (`focus_areas`): the competences that matter most, the first five.
 */
focus: Array<string>, 
/**
 * `wunschrollen[]` (`target_roles`): the roles the consultant is looking for.
 */
roles: Array<string>, 
/**
 * `einsatzpraeferenzen` (`preferences`): wishes, they only nudge the score.
 */
wishes: ProfileWishes, 
/**
 * `harte_kriterien` (with the `einsatzpraeferenzen` fallbacks).
 */
criteria: ProfileCriteria, };
