// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorInfo } from "./ErrorInfo";
import type { ProfileQuality } from "./ProfileQuality";
import type { ProfileUnderstanding } from "./ProfileUnderstanding";

/**
 * The stored consultant profile.
 */
export type ProfileInfo = { 
/**
 * Name of the file the user chose (else the stored file name).
 */
fileName: string, bytes: number, savedAt: string | null, quality: ProfileQuality | null, understood: ProfileUnderstanding | null, scoredAt: string | null, 
/**
 * Jobs still waiting for a score with this profile.
 */
pending: number, 
/**
 * The file is no valid JSON object any more (edited by hand).
 */
parseError: ErrorInfo | null, };
