// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageLevel } from "./LanguageLevel";

/**
 * One language with its level.
 */
export type ProfileLanguage = { language: string, level: LanguageLevel | null, 
/**
 * Index of the entry in the JSON the form was read from; `null` for a new one.
 */
origin: number | null, };
