// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileForm } from "./ProfileForm";
import type { ProfileQuality } from "./ProfileQuality";
import type { ProfileUnderstanding } from "./ProfileUnderstanding";

/**
 * A profile read for the editor from a chosen file or a pasted answer: nothing is stored
 * until the user saves it. `understood` says what the engine reads in it (its warnings
 * show before saving).
 */
export type ProfileDraft = { form: ProfileForm, 
/**
 * The JSON saving merges the form into: the file's or the answer's, for an update from a
 * CV the stored profile with the answer's career stations.
 */
source: string, quality: ProfileQuality, understood: ProfileUnderstanding, };
