// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteWish } from "./RemoteWish";

/**
 * Wishes of the consultant (`einsatzpraeferenzen`): unlike the hard criteria they never
 * exclude a job.
 */
export type ProfileWishes = { 
/**
 * `tagessatz_wunsch` (`desired_day_rate`), EUR per day.
 */
dayRate: number | null, 
/**
 * `remote`.
 */
remote: RemoteWish | null, 
/**
 * `regionen[]` (`regions`), preferred cities or regions.
 */
regions: Array<string>, 
/**
 * `branchen[]` (`industries`) inside `einsatzpraeferenzen`, preferred industries.
 */
industries: Array<string>, };
