// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the consultant is available.
 */
export type ProfileAvailability = { "kind": "unset" } | { "kind": "now" } | { "kind": "from", date: string, };
