// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileAvailability } from "./ProfileAvailability";

/**
 * The hard criteria (a missing value switches its rule off).
 */
export type ProfileCriteria = { 
/**
 * `min_tagessatz` (read with the fallback `einsatzpraeferenzen.tagessatz_ab`).
 */
minDayRate: number | null, 
/**
 * `laender`, ISO codes (`DE`, `AT`, ...).
 */
countries: Array<string>, 
/**
 * `ausgeschlossene_vertragsarten` contains `anue`.
 */
noAnue: boolean, 
/**
 * `verfuegbar_ab`.
 */
available: ProfileAvailability, 
/**
 * `remote_ausserhalb_erlaubt`.
 */
remoteOutside: boolean, 
/**
 * `zielprofil_min_jahre`.
 */
targetYears: number | null, 
/**
 * `min_jahresgehalt` (permanent roles).
 */
minSalary: number | null, 
/**
 * `festanstellung_orte` (permanent roles).
 */
permanentPlaces: Array<string>, 
/**
 * `festanstellung_remote_min`, percent (permanent roles).
 */
permanentRemoteMin: number | null, };
