// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A part of the profile file the terms for the match come from.
 */
export type ProfileSource = { 
/**
 * JSON path pattern (`kernkompetenzen[].kompetenz`, `stationen[].rolle`).
 */
path: string, 
/**
 * Terms read there.
 */
count: number, };
