// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileForm } from "./ProfileForm";
import type { ProfileQuality } from "./ProfileQuality";

/**
 * A profile read for the editor from a chosen file or a pasted answer: nothing is stored
 * until the user saves it.
 */
export type ProfileDraft = { form: ProfileForm, 
/**
 * The JSON the form came from; saving merges the form into it.
 */
source: string, quality: ProfileQuality, };
