// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Quota = { usedHour: number, capHour: number, usedDay: number, capDay: number, };
