// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weight of a reason.
 */
export type ReasonWeight = "must" | "nice" | "hard" | "info";
