// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of a reason in the match explanation.
 */
export type ReasonKind = "met" | "partial" | "open" | "violation" | "check";
