// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";
import type { ReasonKind } from "./ReasonKind";
import type { ReasonWeight } from "./ReasonWeight";
import type { TextRange } from "./TextRange";

/**
 * One reason of the match explanation.
 */
export type Reason = { id: string, kind: ReasonKind, weight: ReasonWeight, code: string, 
/**
 * The requirement as the ad words it (data, not prose of the app).
 */
label: string, evidence: Evidence | null, params: Record<string, string | number | boolean | null>, ranges: Array<TextRange>, };
