// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much remote work the consultant wishes for.
 */
export type RemoteWish = "full" | "mostly" | "partly" | "onSite";
