// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of "reset everything" after the restart.
 */
export type ResetSummary = { removed: number, 
/**
 * Entries that could not be deleted (details in the log).
 */
failed: number, };
