// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Risk of the portal switches: low (public pages), grey (guest access, no account
 * affected), account (signed in - the user's account is at stake).
 */
export type Risk = "low" | "grey" | "account";
