// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobView } from "./JobView";
import type { Portal } from "./Portal";
import type { PortalHealth } from "./PortalHealth";
import type { RunSummary } from "./RunSummary";
import type { StatusCode } from "./StatusCode";
import type { Step } from "./Step";

/**
 * Events to the interface. Each stays small (< 8 KB; bigger messages bypass the ACL of the
 * Tauri channel): full texts and job rows are fetched by the page itself (`list_jobs`,
 * `job_detail`). Struct variants only - with `tag = "type"` a newtype variant would merge
 * into the tag.
 */
export type RunEvent = { "type": "progress", step: Step, portal: Portal | null, done: number, total: number, } | { "type": "status", code: StatusCode, portal: Portal | null, until: string | null, } | { "type": "alert", portal: Portal, subject: string, date: string | null, postings: number, 
/**
 * Gmail message id (hexadecimal) - opened through `open_target`.
 */
gmailId: string | null, } | { "type": "jobUpdated", job: JobView, } | { "type": "portalHealth", portal: Portal, health: PortalHealth, } | { "type": "loginNeeded", portal: Portal, waiting: boolean, } | { "type": "finished", summary: RunSummary, };
