// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The kind of a run without its data (summary, snapshot).
 */
export type RunKindName = "fetch" | "details" | "rescore" | "fullMailbox";
