// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKey } from "./JobKey";

/**
 * The kinds of run.
 */
export type RunKind = { "kind": "fetch" } | { "kind": "details", keys: Array<JobKey>, } | { "kind": "rescore" } | { "kind": "fullMailbox" };
