// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKey } from "./JobKey";

/**
 * What the interface starts. The JSON is flat: `{ "kind": "details", "keys": [...] }`.
 */
export type RunRequest = { "kind": "fetch" } | { "kind": "details", keys: Array<JobKey>, } | { "kind": "rescore" } | { "kind": "fullMailbox" };
