// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunEvent } from "./RunEvent";
import type { RunKindName } from "./RunKindName";

/**
 * A run in progress, for a page that attaches again (reload): what it is and the events
 * that describe its current state (last status and progress, portal health, alerts).
 */
export type RunSnapshot = { kind: RunKindName, startedAt: string, replay: Array<RunEvent>, };
