// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmptyAlert } from "./EmptyAlert";
import type { ExportSummary } from "./ExportSummary";
import type { Outcome } from "./Outcome";
import type { PortalSummary } from "./PortalSummary";
import type { RunKindName } from "./RunKindName";
import type { ScanCounts } from "./ScanCounts";
import type { ScoreSummary } from "./ScoreSummary";

export type RunSummary = { run: number, kind: RunKindName, outcome: Outcome, dryRun: boolean, startedAt: string, finishedAt: string, scan: ScanCounts | null, perPortal: Array<PortalSummary>, score: ScoreSummary | null, export: ExportSummary | null, 
/**
 * Alert mails of this run without recognised jobs (at most [`MAX_EMPTY_ALERTS`]).
 */
emptyAlerts: Array<EmptyAlert>, };
