// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters of the mailbox step. Invariant: `postings = new + known + dup`.
 */
export type ScanCounts = { mailsFound: number, mailsChecked: number, 
/**
 * Unreadable mails (counted instead of dropped silently).
 */
mailsDefective: number, alertMails: number, 
/**
 * Alert mails without a recognised job (layout changed?).
 */
emptyAlerts: number, postings: number, new: number, known: number, dup: number, };
