// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counters of the score step.
 */
export type ScoreSummary = { scored: number, excluded: number, unscorable: number, 
/**
 * Jobs still waiting for a score.
 */
pending: number, best: number | null, };
