// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortalPatch } from "./PortalPatch";

/**
 * Changes of the settings. `null` = unchanged; the workspace only changes through the
 * folder dialog (`pick_workspace`).
 */
export type SettingsPatch = { portals: Array<PortalPatch>, autoFetchOnStart: boolean | null, 
/**
 * Days after which old jobs archive themselves; 0 = never (`null` = unchanged).
 */
autoArchiveDays: number | null, 
/**
 * Days after which the trash empties itself; 0 = never (`null` = unchanged).
 */
autoEmptyTrashDays: number | null, };
