// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsView = { 
/**
 * Effective workspace (chosen or default).
 */
workspace: string, workspaceIsDefault: boolean, 
/**
 * Number of the app's text files - exactly what "delete text files" removes.
 */
txtFiles: number, excelExists: boolean, };
