// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is happening right now.
 */
export type StatusCode = "connectingMail" | "searchingMail" | "readingMails" | "fetchingDetails" | "signingIn" | "waiting" | "scoring" | "writingFiles";
