// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range in the full text, in UTF-16 code units (as the browser counts).
 */
export type TextRange = { start: number, end: number, };
