// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A field of the form that can hold a value the engine could not read from the file
 * (`criterionNotUnderstood`, `availabilityNotUnderstood`). "Wert entfernen" names it: saving
 * then removes every key behind it wherever the engine reads it.
 */
export type UnreadableField = "minDayRate" | "countries" | "contracts" | "remoteOutside" | "available" | "targetYears" | "minSalary" | "permanentPlaces" | "permanentRemoteMin" | "focus" | "roles" | "wishDayRate" | "remote" | "regions" | "wishIndustries";
