// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the job is done, as far as the location field says.
 */
export type WorkMode = "remote" | "hybrid" | "onsite";
