//! Word lists of the matching engine.
//!
//! external contract - do not translate: these are German and English words as they
//! appear in job ads and consultant profiles. The legacy tables are copied verbatim from
//! the old Python engine (`ca9a2cd^:matcher.py`) and checked against
//! `core/tests/fixtures/matching/legacy_lexicon.json` by the tests. Sorted tables are
//! searched with `binary_search`; keep them sorted.

/// Tokens that never count as a skill (sorted).
pub(crate) const STOPWORDS: &[&str] = &[
    "aber",
    "abgeschlossene",
    "abgeschlossenes",
    "ability",
    "across",
    "all",
    "alle",
    "allen",
    "als",
    "also",
    "an",
    "and",
    "apply",
    "are",
    "auch",
    "auf",
    "aus",
    "ausgepraegte",
    "ausgeprägte",
    "been",
    "bei",
    "benoetigt",
    "benötigt",
    "berufliche",
    "betriebliche",
    "bitte",
    "but",
    "bzw",
    "ca",
    "can",
    "could",
    "das",
    "dem",
    "den",
    "der",
    "des",
    "die",
    "diese",
    "dieser",
    "dieses",
    "du",
    "durch",
    "eigenverantwortlich",
    "eigenverantwortliche",
    "ein",
    "eine",
    "einem",
    "einer",
    "eines",
    "einschlaegige",
    "einschlaegigen",
    "einschlägige",
    "einschlägigen",
    "er",
    "erfahrung",
    "erfahrungen",
    "erfahrungswissen",
    "erfolgreich",
    "erfolgreiche",
    "erforderlich",
    "erforderliche",
    "erste",
    "erster",
    "es",
    "etc",
    "excellent",
    "experience",
    "fliessend",
    "fliessende",
    "fließend",
    "fließende",
    "fluent",
    "for",
    "from",
    "fundiert",
    "fundierte",
    "fur",
    "für",
    "gern",
    "gerne",
    "gesucht",
    "good",
    "gute",
    "guten",
    "guter",
    "gutes",
    "haben",
    "had",
    "handson",
    "has",
    "hat",
    "hatte",
    "have",
    "idealerweise",
    "ihr",
    "ihre",
    "ihrem",
    "ihren",
    "ihrer",
    "ihres",
    "im",
    "in",
    "including",
    "into",
    "ist",
    "jede",
    "jeder",
    "jedes",
    "job",
    "jobs",
    "kann",
    "kein",
    "keine",
    "kenntnis",
    "kenntnisse",
    "knowledge",
    "konnen",
    "können",
    "langjaehrig",
    "langjaehrige",
    "langjährig",
    "langjährige",
    "m/f/d",
    "m/w",
    "m/w/d",
    "may",
    "mehrjaehrig",
    "mehrjaehrige",
    "mehrjährig",
    "mehrjährige",
    "mit",
    "more",
    "most",
    "muss",
    "mussen",
    "must",
    "muttersprachliche",
    "mwd",
    "müssen",
    "nach",
    "nachgewiesene",
    "native",
    "neue",
    "neuen",
    "neuer",
    "new",
    "nicht",
    "not",
    "now",
    "oder",
    "ohne",
    "our",
    "over",
    "per",
    "please",
    "practical",
    "praktisch",
    "praktische",
    "praxis",
    "praxiserfahrung",
    "previous",
    "prior",
    "proficient",
    "proven",
    "relevant",
    "relevante",
    "required",
    "requirements",
    "role",
    "sehr",
    "sein",
    "seine",
    "selbststaendige",
    "selbstständig",
    "selbstständige",
    "should",
    "sich",
    "sichere",
    "sicherer",
    "sicheres",
    "sie",
    "sind",
    "skill",
    "skills",
    "solid",
    "solide",
    "soll",
    "sollen",
    "souveraene",
    "souveräne",
    "sowie",
    "strong",
    "suchen",
    "team",
    "that",
    "the",
    "their",
    "them",
    "they",
    "this",
    "tiefgehende",
    "uber",
    "um",
    "umfangreiche",
    "umfassend",
    "umfassende",
    "umgang",
    "und",
    "under",
    "unter",
    "usw",
    "verhandlungssicher",
    "verhandlungssichere",
    "von",
    "vorausgesetzt",
    "w/m/d",
    "war",
    "waren",
    "was",
    "weil",
    "weitere",
    "weiteren",
    "wenn",
    "werden",
    "were",
    "wie",
    "will",
    "wir",
    "wird",
    "wissen",
    "with",
    "within",
    "worden",
    "work",
    "working",
    "would",
    "wurde",
    "wurden",
    "years",
    "you",
    "your",
    "zu",
    "zum",
    "zur",
    "zwischen",
    "über",
];

/// Word-level synonyms: variant -> canonical form; `None` drops the token (sorted by variant).
pub(crate) const SYNONYM_WORDS: &[(&str, Option<&str>)] = &[
    ("agil", Some("agil")),
    ("agile", Some("agil")),
    ("ai", Some("ki")),
    ("beratung", Some("beratung")),
    ("bi", Some("bi")),
    ("c#", Some("c#")),
    ("carveout", Some("carve-out")),
    ("changekommunikation", Some("change-kommunikation")),
    ("changemanagement", Some("changemanagement")),
    ("changemanagment", Some("changemanagement")),
    ("co", Some("co")),
    ("consulting", Some("beratung")),
    ("fi", Some("fi")),
    ("führungsentwicklung", Some("leadershipdevelopment")),
    ("hana", None),
    ("hr", Some("hr")),
    ("interimmanagement", Some("interimmanagement")),
    ("ki", Some("ki")),
    ("leadershipdevelopment", Some("leadershipdevelopment")),
    ("mm", Some("mm")),
    ("organisationsentwicklung", Some("organisationsentwicklung")),
    (
        "organizationaldevelopment",
        Some("organisationsentwicklung"),
    ),
    ("pi", Some("pi")),
    ("pm", Some("pm")),
    ("po", Some("po")),
    ("pp", Some("pp")),
    ("projectlead", Some("projektleitung")),
    ("projectmanagement", Some("projektmanagement")),
    ("projektleiter", Some("projektleitung")),
    ("projektleiterin", Some("projektleitung")),
    ("projektleitung", Some("projektleitung")),
    ("projektmanagement", Some("projektmanagement")),
    ("qa", Some("qa")),
    ("qm", Some("qm")),
    ("restructuring", Some("restrukturierung")),
    ("restrukturierung", Some("restrukturierung")),
    ("s4", Some("s/4hana")),
    ("s4/hana", Some("s/4hana")),
    ("s4hana", Some("s/4hana")),
    ("sd", Some("sd")),
    ("stakeholdermanagement", Some("stakeholdermanagement")),
    ("tm", Some("tm")),
    ("training", Some("weiterbildung")),
    ("ui", Some("ui")),
    ("ux", Some("ux")),
    ("weiterbildung", Some("weiterbildung")),
    ("wm", Some("wm")),
];

/// Adjacent token pairs merged into one canonical token (sorted by pair).
pub(crate) const SYNONYM_PAIRS: &[(&str, &str, &str)] = &[
    ("agile", "methoden", "agilemethoden"),
    ("business", "partner", "businesspartner"),
    ("carve", "out", "carve-out"),
    ("change", "kommunikation", "change-kommunikation"),
    ("change", "management", "changemanagement"),
    ("change", "managment", "changemanagement"),
    ("design", "thinking", "designthinking"),
    ("hr", "transformation", "hr-transformation"),
    ("interim", "management", "interimmanagement"),
    ("leadership", "development", "leadershipdevelopment"),
    ("operating", "model", "operatingmodel"),
    ("organisations", "entwicklung", "organisationsentwicklung"),
    ("project", "lead", "projektleitung"),
    ("project", "management", "projektmanagement"),
    ("project", "manager", "projektmanagement"),
    ("projekt", "leitung", "projektleitung"),
    ("projekt", "management", "projektmanagement"),
    ("s4", "hana", "s/4hana"),
    ("stakeholder", "management", "stakeholdermanagement"),
];

/// Headings of requirement sections (sorted).
pub(crate) const MUST_HEADINGS: &[&str] = &[
    "anforderung",
    "anforderungen",
    "anforderungsprofil",
    "berufserfahrung",
    "das bringen sie mit",
    "das bringst du mit",
    "dein anforderungsprofil",
    "dein profil",
    "deine qualifikationen",
    "du bringst mit",
    "erfahrung",
    "erfahrungen",
    "erforderliche kenntnisse",
    "erforderliche qualifikationen",
    "fachkenntnisse",
    "fachliche anforderungen",
    "fachliche qualifikationen",
    "fachliche voraussetzungen",
    "gesuchtes profil",
    "gewünschtes profil",
    "ihr anforderungsprofil",
    "ihr profil",
    "ihr qualifikationsprofil",
    "ihre qualifikationen",
    "kenntnisse",
    "kenntnisse und erfahrungen",
    "key requirements",
    "minimum qualifications",
    "muss-kriterien",
    "must have",
    "must-have",
    "profil",
    "qualifications",
    "qualifikation",
    "qualifikationen",
    "qualifikationsprofil",
    "required skills",
    "requirements",
    "sie bringen mit",
    "skills",
    "skills and experience",
    "voraussetzung",
    "voraussetzungen",
    "was dich auszeichnet",
    "was du mitbringst",
    "was sie auszeichnet",
    "was sie mitbringen",
    "was sie mitbringen sollten",
    "was wir erwarten",
    "was wir suchen",
    "what we are looking for",
    "what you bring",
    "your experience",
    "your profile",
];

/// Headings of nice-to-have sections (sorted).
pub(crate) const NICE_HEADINGS: &[&str] = &[
    "bonus",
    "bonusqualifikation",
    "darüber hinaus von vorteil",
    "desirable",
    "good to have",
    "ideal",
    "idealerweise",
    "nice to have",
    "nice to haves",
    "nice-to-have",
    "plus",
    "pluspunkte",
    "preferred qualifications",
    "von vorteil",
    "von vorteil sind",
    "von vorteil wäre",
    "vorteile sind",
    "vorteilhaft",
    "vorteilhaft sind",
    "wuenschenswert",
    "wünschenswert",
    "wünschenswerte erfahrungen",
    "wünschenswerte kenntnisse",
    "wünschenswerte qualifikationen",
    "wünschenswerte voraussetzungen",
    "wünschenswertes profil",
    "zusatzlich von vorteil",
    "zusätzlich von vorteil",
];

/// Headings of task sections (sorted).
pub(crate) const TASK_HEADINGS: &[&str] = &[
    "about the job",
    "aufgaben",
    "aufgaben und verantwortlichkeiten",
    "aufgabengebiet",
    "aufgabengebiete",
    "aufgabenschwerpunkte",
    "aufgabenstellung",
    "ausgangslage",
    "beschreibung",
    "das erwartet dich",
    "das erwartet sie",
    "deine aufgaben",
    "deine hauptaufgaben",
    "deine mission",
    "deine rolle",
    "deine tätigkeit",
    "einsatz",
    "einsatzbeschreibung",
    "hintergrund",
    "ihre aufgaben",
    "ihre hauptaufgaben",
    "ihre mission",
    "ihre rolle",
    "ihre tätigkeit",
    "ihre verantwortung",
    "job description",
    "jobbeschreibung",
    "leistungsbeschreibung",
    "project description",
    "projektbeschreibung",
    "projektinhalt",
    "projektinhalte",
    "rahmenbedingungen",
    "responsibilities",
    "scope of work",
    "stellenbeschreibung",
    "taetigkeiten",
    "taetigkeitsbeschreibung",
    "tasks",
    "the role",
    "tätigkeiten",
    "tätigkeitsbeschreibung",
    "ueber das projekt",
    "ueber die aufgabe",
    "verantwortlichkeiten",
    "verantwortungsbereich",
    "was dich erwartet",
    "was sie erwartet",
    "what you will do",
    "what you'll do",
    "your responsibilities",
    "your role",
    "your tasks",
    "über das projekt",
    "über die aufgabe",
    "über die aufgaben",
];

/// Headings of neutral sections (sorted).
pub(crate) const NEUTRAL_HEADINGS: &[&str] = &[
    "about us",
    "ansprechpartner",
    "arbeitsumfeld",
    "benefits",
    "bewerbung",
    "bewerbungsprozess",
    "das bieten wir",
    "das unternehmen",
    "deine benefits",
    "firmenprofil",
    "ihre benefits",
    "kontakt",
    "so bewirbst du dich",
    "ueber das unternehmen",
    "ueber uns",
    "ueber unseren kunden",
    "unser angebot",
    "unternehmen",
    "unternehmensprofil",
    "warum du zu uns",
    "warum wir",
    "was wir bieten",
    "wer wir sind",
    "what we offer",
    "why join us",
    "wir bieten",
    "wir sind",
    "wir über uns",
    "über das unternehmen",
    "über den auftraggeber",
    "über die firma",
    "über uns",
    "über unseren kunden",
];

/// Vocabulary of the last fallback, in the old order (the order breaks ties).
pub(crate) const JOB_SKILL_VOCAB: &[&str] = &[
    "sap",
    "sap s/4hana",
    "sap hana",
    "sap fi/co",
    "sap fi co",
    "sap co",
    "sap sd",
    "sap mm",
    "sap pp",
    "sap wm",
    "sap ewm",
    "sap tm",
    "sap bw",
    "sap bi",
    "sap bw/4hana",
    "sap btp",
    "sap fiori",
    "sap grc",
    "abap",
    "bapi",
    "idoc",
    "alv",
    "lsmw",
    "sapscript",
    "smartforms",
    "fscm",
    "treasury",
    "salesforce",
    "servicenow",
    "workday",
    "dynamics 365",
    "microsoft dynamics",
    "crm",
    "erp",
    "mes",
    "plm",
    "dms",
    "ecm",
    "wms",
    "tms",
    "power bi",
    "tableau",
    "qlik",
    "qlik sense",
    "sql",
    "pl/sql",
    "oracle",
    "postgresql",
    "mongodb",
    "data warehouse",
    "dwh",
    "business intelligence",
    "reporting",
    "dashboarding",
    "kpi",
    "etl",
    "ssis",
    "ssrs",
    "databricks",
    "snowflake",
    "data analytics",
    "data science",
    "machine learning",
    "stammdaten",
    "master data",
    "mdm",
    "datenqualität",
    "datenqualitaet",
    "datenmigration",
    "data migration",
    "java",
    "python",
    "javascript",
    "typescript",
    "angular",
    "react",
    "node js",
    "php",
    "spark",
    "kafka",
    "aws",
    "azure",
    "google cloud",
    "gcp",
    "kubernetes",
    "docker",
    "terraform",
    "devops",
    "jenkins",
    "gitlab",
    "rest api",
    "api",
    "soap",
    "xml",
    "json",
    "edi",
    "cobol",
    "mainframe",
    "cics",
    "vba",
    "excel",
    "sharepoint",
    "microsoft 365",
    "m365",
    "jira",
    "confluence",
    "hp alm",
    "tosca",
    "uft",
    "postman",
    "swagger",
    "cloud",
    "iot",
    "rpa",
    "automatisierung",
    "projektmanagement",
    "programmmanagement",
    "portfoliomanagement",
    "multiprojektmanagement",
    "scrum",
    "kanban",
    "safe",
    "less",
    "itil",
    "pmbok",
    "prince2",
    "hermes",
    "ipma",
    "pmp",
    "lean",
    "six sigma",
    "kaizen",
    "design thinking",
    "requirements engineering",
    "anforderungsmanagement",
    "testmanagement",
    "release management",
    "changemanagement",
    "business transformation",
    "transformation",
    "digitalisierung",
    "digitale transformation",
    "migration",
    "rollout",
    "go-live",
    "hypercare",
    "application management",
    "schnittstellen",
    "integration",
    "prozessoptimierung",
    "prozessmanagement",
    "bpmn",
    "process mining",
    "celonis",
    "signavio",
    "aris",
    "enterprise architecture",
    "togaf",
    "it-strategie",
    "it-architektur",
    "informationssicherheit",
    "iso 27001",
    "it-grundschutz",
    "dsgvo",
    "gdpr",
    "datenschutz",
    "identity management",
    "iam",
    "active directory",
    "netzwerk",
    "firewall",
    "controlling",
    "finance",
    "rechnungswesen",
    "buchhaltung",
    "hgb",
    "ifrs",
    "us-gaap",
    "konsolidierung",
    "bilanzierung",
    "forecast",
    "budgetierung",
    "risikomanagement",
    "compliance",
    "governance",
    "sox",
    "interne revision",
    "wirtschaftsprüfung",
    "wirtschaftspruefung",
    "lohnbuchhaltung",
    "personalabrechnung",
    "human resources",
    "recruiting",
    "e-learning",
    "logistik",
    "supply chain",
    "scm",
    "einkauf",
    "beschaffung",
    "procurement",
    "produktion",
    "manufacturing",
    "e-commerce",
    "ecommerce",
    "qualitätsmanagement",
    "qualitaetsmanagement",
    "iso 9001",
    "gmp",
    "validierung",
    "pharma",
    "chemie",
    "automotive",
    "fertigung",
    "energie",
    "versicherung",
    "banken",
    "gesundheitswesen",
    "öffentlicher sektor",
    "oeffentlicher sektor",
    "deutsch",
    "englisch",
    "english",
    "französisch",
    "franzoesisch",
    "spanisch",
    "italienisch",
    "niederländisch",
    "niederlaendisch",
    "polnisch",
    "türkisch",
    "tuerkisch",
    "russisch",
    "chinesisch",
    "portugiesisch",
];

/// Profile keys whose strings are skill lists (sorted).
pub(crate) const SKILL_KEYS: &[&str] = &[
    "fachkenntnisse",
    "faehigkeiten",
    "kenntnisse",
    "kompetenzen",
    "methoden",
    "methodik",
    "qualifikationen",
    "schwerpunkte",
    "skills",
    "technologien",
    "techstack",
    "tools",
    "zertifikate",
    "zertifizierungen",
];

/// Profile keys that never take part in matching (sorted).
pub(crate) const PERSONAL_KEYS: &[&str] = &[
    "adresse",
    "alter",
    "e-mail",
    "email",
    "foto",
    "geburtsdatum",
    "handy",
    "homepage",
    "kontakt",
    "kundennummer",
    "linkedin",
    "mitgliedsnummer",
    "mobil",
    "nachname",
    "name",
    "plz",
    "profilbild",
    "strasse",
    "telefon",
    "verfuegbarkeit",
    "vorname",
    "website",
    "xing",
];

/// Profile keys whose strings are core competences (sorted).
pub(crate) const CORE_KEYS: &[&str] = &[
    "abschluss",
    "alleinstellungsmerkmal",
    "branche",
    "certification",
    "kernkompetenz",
    "keyword",
    "keywords",
    "kompetenz",
    "skill",
    "sprache",
    "titel",
    "zertifizierung",
];

/// Profile keys with soft evidence such as quotes (sorted).
pub(crate) const SOFT_KEYS: &[&str] = &["testimonial", "zitat"];

/// Country names found anywhere in a job text and their ISO codes (sorted by name).
pub(crate) const COUNTRY_NAMES: &[(&str, &str)] = &[
    ("austria", "AT"),
    ("czech", "CZ"),
    ("deutschland", "DE"),
    ("england", "GB"),
    ("france", "FR"),
    ("frankreich", "FR"),
    ("germany", "DE"),
    ("india", "IN"),
    ("indien", "IN"),
    ("italien", "IT"),
    ("italy", "IT"),
    ("netherlands", "NL"),
    ("niederlande", "NL"),
    ("oesterreich", "AT"),
    ("poland", "PL"),
    ("polen", "PL"),
    ("schweiz", "CH"),
    ("spain", "ES"),
    ("spanien", "ES"),
    ("switzerland", "CH"),
    ("tschechien", "CZ"),
    ("uk", "GB"),
    ("usa", "US"),
    ("österreich", "AT"),
];
