//! Word lists of the consultant's wishes: target roles, remote work, regions and
//! industries (`ENGINE_VERSION` 4).
//!
//! external contract - do not translate: German and English wording of job ads and of the
//! values a profile writes into `einsatzpraeferenzen`. All entries are case-folded and
//! without umlauts (`fold`).

/// Title words that mark a leading role (whole words); compounds ending in `leiter`,
/// `leiterin` or `leitung` lead as well.
pub(crate) const LEAD_WORDS: &[&str] = &[
    "chief",
    "director",
    "direktor",
    "direktorin",
    "head",
    "lead",
    "leiter",
    "leiterin",
    "leitung",
    "vp",
];
/// Compound endings of a leading role (`Bereichsleiter`, `Gesamtprojektleitung`).
pub(crate) const LEAD_ENDINGS: &[&str] = &["leiter", "leiterin", "leitung"];
/// Title words of a level that a target role neither needs nor excludes.
pub(crate) const LEVEL_WORDS: &[&str] = &["principal", "senior", "sme", "expert", "experte"];
/// Words of a contract type inside a target role (`Interim CFO`): met by the title or by
/// an interim contract.
pub(crate) const ROLE_CONTRACT_WORDS: &[&str] = &[
    "freelance",
    "freelancer",
    "freiberufler",
    "freiberuflich",
    "interim",
    "interimistisch",
];
/// Paraphrases of a role title, applied to role and title before they are compared
/// (phrase -> replacement, whole words).
pub(crate) const ROLE_PHRASES: &[(&str, &str)] = &[
    ("chief financial officer", "cfo"),
    ("finanzvorstand", "cfo"),
    ("finanzvorstandin", "cfo"),
    ("kaufmannischer geschaftsfuhrer", "cfo"),
    ("kaufmannische geschaftsfuhrerin", "cfo"),
    ("kaufmannische geschaftsfuhrung", "cfo"),
    ("head of", "head"),
    ("leiter der", "leiter"),
    ("leiterin der", "leiterin"),
    ("leitung der", "leitung"),
    ("leitung des", "leitung"),
    ("finanzen", "finance"),
    ("finanzbereich", "finance"),
];

/// Words of remote work in an ad (whole words or word starts).
pub(crate) const REMOTE_AD_WORDS: &[&str] = &[
    "remote",
    "homeoffice",
    "home-office",
    "home office",
    "mobile",
    "mobilem",
    "mobilen",
    "mobiles",
    "mobil arbeiten",
    "work from home",
    "telearbeit",
];
/// Words of presence at the client.
pub(crate) const ONSITE_AD_WORDS: &[&str] = &[
    "vor ort",
    "on site",
    "on-site",
    "onsite",
    "prasenz",
    "im buro",
    "in the office",
    "im office",
];
/// No remote work at all.
pub(crate) const REMOTE_NONE: &[&str] = &[
    "kein remote",
    "keine remote",
    "kein homeoffice",
    "keine homeoffice",
    "kein home-office",
    "no remote",
    "remote nicht moglich",
    "remote ist nicht moglich",
    "not remote",
];
/// Hybrid work without a share.
pub(crate) const HYBRID_WORDS: &[&str] = &[
    "hybrid",
    "teilweise remote",
    "anteilig remote",
    "partly remote",
    "partially remote",
    "mobiles arbeiten",
    "mobilem arbeiten",
    "homeoffice moglich",
    "home office moglich",
    "homeoffice-anteil",
];
/// Days of a week (`zwei Tage vor Ort`).
pub(crate) const DAY_WORDS: &[&str] = &["tag", "tage", "tagen", "day", "days"];
/// Small numbers written as words (days of a week).
pub(crate) const DAY_NUMBERS: &[(&str, u64)] = &[
    ("ein", 1),
    ("einen", 1),
    ("einem", 1),
    ("eins", 1),
    ("one", 1),
    ("zwei", 2),
    ("two", 2),
    ("drei", 3),
    ("three", 3),
    ("vier", 4),
    ("four", 4),
];

/// German states and larger regions with the larger places inside them (for regions of a
/// profile such as `Bayern` or `Rhein-Main`).
pub(crate) const REGION_PLACES: &[(&str, &[&str])] = &[
    (
        "bayern",
        &[
            "munchen",
            "augsburg",
            "nurnberg",
            "regensburg",
            "ingolstadt",
            "wurzburg",
            "erlangen",
            "furth",
            "bamberg",
            "bayreuth",
            "landshut",
            "rosenheim",
            "passau",
            "freising",
            "erding",
            "garching",
            "unterschleissheim",
        ],
    ),
    (
        "bavaria",
        &[
            "munchen",
            "augsburg",
            "nurnberg",
            "regensburg",
            "ingolstadt",
            "wurzburg",
            "erlangen",
            "furth",
            "bamberg",
            "bayreuth",
            "landshut",
            "rosenheim",
            "passau",
        ],
    ),
    (
        "baden-wurttemberg",
        &[
            "stuttgart",
            "karlsruhe",
            "mannheim",
            "freiburg",
            "heidelberg",
            "ulm",
            "heilbronn",
            "pforzheim",
            "reutlingen",
        ],
    ),
    (
        "hessen",
        &[
            "frankfurt",
            "wiesbaden",
            "kassel",
            "darmstadt",
            "offenbach",
            "marburg",
            "giessen",
            "hanau",
        ],
    ),
    (
        "nordrhein-westfalen",
        &[
            "koln",
            "dusseldorf",
            "dortmund",
            "essen",
            "duisburg",
            "bochum",
            "bonn",
            "munster",
            "bielefeld",
            "aachen",
            "wuppertal",
            "gelsenkirchen",
            "monchengladbach",
            "krefeld",
            "oberhausen",
            "hagen",
            "paderborn",
            "leverkusen",
        ],
    ),
    (
        "nrw",
        &[
            "koln",
            "dusseldorf",
            "dortmund",
            "essen",
            "duisburg",
            "bochum",
            "bonn",
            "munster",
            "bielefeld",
            "aachen",
            "wuppertal",
            "gelsenkirchen",
            "monchengladbach",
            "krefeld",
            "oberhausen",
            "hagen",
            "paderborn",
            "leverkusen",
        ],
    ),
    (
        "niedersachsen",
        &[
            "hannover",
            "braunschweig",
            "osnabruck",
            "oldenburg",
            "gottingen",
            "wolfsburg",
            "hildesheim",
        ],
    ),
    ("sachsen", &["leipzig", "dresden", "chemnitz", "zwickau"]),
    (
        "rheinland-pfalz",
        &[
            "mainz",
            "ludwigshafen",
            "koblenz",
            "trier",
            "kaiserslautern",
        ],
    ),
    ("schleswig-holstein", &["kiel", "lubeck", "flensburg"]),
    ("thuringen", &["erfurt", "jena", "gera", "weimar"]),
    ("sachsen-anhalt", &["magdeburg", "halle"]),
    ("brandenburg", &["potsdam", "cottbus"]),
    ("mecklenburg-vorpommern", &["rostock", "schwerin"]),
    ("saarland", &["saarbrucken"]),
    ("berlin", &["berlin"]),
    ("hamburg", &["hamburg"]),
    ("bremen", &["bremen", "bremerhaven"]),
    (
        "rhein-main",
        &[
            "frankfurt",
            "wiesbaden",
            "mainz",
            "darmstadt",
            "offenbach",
            "hanau",
        ],
    ),
    (
        "ruhrgebiet",
        &[
            "essen",
            "dortmund",
            "duisburg",
            "bochum",
            "gelsenkirchen",
            "oberhausen",
            "hagen",
        ],
    ),
    ("rhein-neckar", &["mannheim", "heidelberg", "ludwigshafen"]),
];

/// Headings of task sections (normalised heading starts): the tasks of a role say little
/// about the client's industry (`Gespräche mit den Banken`).
pub(crate) const TASK_HEADINGS: &[&str] = &[
    "aufgaben",
    "deine aufgaben",
    "deine rolle",
    "ihr aufgabengebiet",
    "ihre aufgaben",
    "ihre rolle",
    "ihre tatigkeiten",
    "responsibilities",
    "tasks",
    "tatigkeiten",
    "what you will do",
    "what you'll do",
    "your responsibilities",
    "your role",
    "your tasks",
];

/// Industries named by a whole word only (a longer word is something else: a bank relation
/// is no bank, a media break no media company).
pub(crate) const INDUSTRY_WORDS: &[(&str, &str)] = &[
    ("bank", "banking"),
    ("banken", "banking"),
    ("food", "food"),
    ("medien", "media"),
    ("media", "media"),
];

/// Industries: a word (a whole folded word, the start of a longer word from six letters on,
/// or a phrase with a space) and its industry.
pub(crate) const INDUSTRIES: &[(&str, &str)] = &[
    ("maschinenbau", "machinery"),
    ("anlagenbau", "machinery"),
    ("machinery", "machinery"),
    ("mechanical engineering", "machinery"),
    ("automobil", "automotive"),
    ("automotive", "automotive"),
    ("fahrzeugbau", "automotive"),
    ("fahrzeughersteller", "automotive"),
    ("autozulieferer", "automotive"),
    ("chemie", "chemicals"),
    ("chemical", "chemicals"),
    ("pharma", "pharma"),
    ("biotech", "pharma"),
    ("life science", "pharma"),
    ("medizintechnik", "medtech"),
    ("medtech", "medtech"),
    ("medical device", "medtech"),
    ("krankenhaus", "healthcare"),
    ("klinik", "healthcare"),
    ("gesundheitswesen", "healthcare"),
    ("healthcare", "healthcare"),
    ("hospital", "healthcare"),
    ("banking", "banking"),
    ("bankwesen", "banking"),
    ("bankensektor", "banking"),
    ("sparkasse", "banking"),
    ("kreditinstitut", "banking"),
    ("finanzdienstleister", "banking"),
    ("financial services", "banking"),
    ("versicherung", "insurance"),
    ("versicherer", "insurance"),
    ("insurance", "insurance"),
    ("insurer", "insurance"),
    ("einzelhandel", "retail"),
    ("handelsunternehmen", "retail"),
    ("handelskonzern", "retail"),
    ("handelsgruppe", "retail"),
    ("grosshandel", "retail"),
    ("retail", "retail"),
    ("e-commerce", "retail"),
    ("energie", "energy"),
    ("energy", "energy"),
    ("stadtwerke", "energy"),
    ("utilities", "energy"),
    ("logistik", "logistics"),
    ("logistics", "logistics"),
    ("spedition", "logistics"),
    ("lebensmittel", "food"),
    ("nahrungsmittel", "food"),
    ("getranke", "food"),
    ("konsumguter", "consumer"),
    ("consumer goods", "consumer"),
    ("fmcg", "consumer"),
    ("telekommunikation", "telecom"),
    ("telecommunication", "telecom"),
    ("telco", "telecom"),
    ("offentliche verwaltung", "public"),
    ("offentlichen verwaltung", "public"),
    ("offentlichen dienst", "public"),
    ("public sector", "public"),
    ("behorde", "public"),
    ("kommunal", "public"),
    ("immobilien", "realEstate"),
    ("real estate", "realEstate"),
    ("bauindustrie", "construction"),
    ("baubranche", "construction"),
    ("bauunternehmen", "construction"),
    ("construction", "construction"),
    ("luftfahrt", "aerospace"),
    ("aerospace", "aerospace"),
    ("raumfahrt", "aerospace"),
    ("private equity", "privateEquity"),
    ("private-equity", "privateEquity"),
    ("portfoliounternehmen", "privateEquity"),
    ("finanzinvestor", "privateEquity"),
    ("beteiligungsgesellschaft", "privateEquity"),
    ("verlagshaus", "media"),
    ("verlagsgruppe", "media"),
    ("elektronik", "electronics"),
    ("halbleiter", "electronics"),
    ("semiconductor", "electronics"),
    ("electronics", "electronics"),
    ("software", "software"),
    ("systemhaus", "software"),
    ("it-dienstleister", "software"),
];
