//! Contract tests of the IPC: every command appears identically in the `AppManifest`
//! (`build.rs`), in `generate_handler!` (`src-tauri/src/commands/mod.rs`), as `allow-...` in
//! the capability of the main window and in the generated TypeScript command map
//! (`ui/src/lib/ipc/types/commands.ts`) - a typo would otherwise only show at runtime as
//! "command not allowed". The map is written here from the `COMMANDS` table; the types it
//! names are generated by `core/src/view/ts.rs`.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn repo(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(relative)
}

fn read(relative: &str) -> String {
    std::fs::read_to_string(repo(relative)).unwrap_or_else(|e| panic!("{relative}: {e}"))
}

/// The text between `start` and the next `end`.
fn between<'a>(text: &'a str, start: &str, end: &str) -> &'a str {
    let from = text.find(start).unwrap_or_else(|| panic!("{start}")) + start.len();
    let to = from + text[from..].find(end).unwrap_or_else(|| panic!("{end}"));
    &text[from..to]
}

/// All string literals of a piece of Rust source, in order.
fn literals(text: &str) -> Vec<String> {
    text.split('"')
        .skip(1)
        .step_by(2)
        .map(str::to_string)
        .collect()
}

/// `(name, arguments, result)` of every command from the table in `commands/mod.rs`.
fn command_table() -> Vec<(String, String, String)> {
    let source = read("src-tauri/src/commands/mod.rs");
    let table = between(&source, "pub const COMMANDS", "];");
    let table = &table[table.find("= [").expect("table start")..];
    let values = literals(table);
    assert_eq!(values.len() % 3, 0, "name, arguments, result per command");
    values
        .chunks(3)
        .map(|c| (c[0].clone(), c[1].clone(), c[2].clone()))
        .collect()
}

fn handler_names() -> BTreeSet<String> {
    let source = read("src-tauri/src/commands/mod.rs");
    between(&source, "generate_handler![", "]")
        .split(',')
        .map(str::trim)
        .filter(|entry| !entry.is_empty())
        .map(|entry| entry.rsplit("::").next().unwrap().to_string())
        .collect()
}

/// The TypeScript command map for the table.
fn commands_ts(table: &[(String, String, String)]) -> String {
    let types: BTreeSet<String> = std::fs::read_dir(repo("ui/src/lib/ipc/types"))
        .expect("generated types (cargo test -p jobalert-core ipc_types)")
        .filter_map(|e| {
            let name = e.ok()?.file_name().to_string_lossy().into_owned();
            let module = name.strip_suffix(".ts")?.to_string();
            (module != "index" && module != "commands").then_some(module)
        })
        .collect();
    let used: BTreeSet<&String> = types
        .iter()
        .filter(|t| {
            table.iter().any(|(_, args, result)| {
                format!("{args} {result}")
                    .split(|c: char| !c.is_ascii_alphanumeric())
                    .any(|word| word == t.as_str())
            })
        })
        .collect();
    let mut out = String::from(
        "// Generated by core/tests/contract.rs from the command table in \
         src-tauri/src/commands/mod.rs. Do not edit.\n\
         import type { Channel } from \"@tauri-apps/api/core\";\n",
    );
    for t in &used {
        let _ = writeln!(out, "import type {{ {t} }} from \"./{t}\";");
    }
    out.push_str(
        "\n/** Every IPC command: its arguments and its result. */\nexport type Commands = {\n",
    );
    for (name, args, result) in table {
        let _ = writeln!(out, "  {name}: {{ args: {args}; result: {result} }};");
    }
    out.push_str("};\n");
    out
}

#[test]
fn command_names_agree_everywhere() {
    let table = command_table();
    let names: BTreeSet<String> = table.iter().map(|(n, ..)| n.clone()).collect();
    assert_eq!(names.len(), table.len(), "no command twice");

    let build = read("src-tauri/build.rs");
    let manifest: BTreeSet<String> = literals(between(&build, ".commands(&[", "])"))
        .into_iter()
        .collect();

    let capability: serde_json::Value =
        serde_json::from_str(&read("src-tauri/capabilities/main.json")).unwrap();
    let allowed: BTreeSet<String> = capability["permissions"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|p| p.as_str()?.strip_prefix("allow-"))
        .map(|p| p.replace('-', "_"))
        .collect();
    assert_eq!(
        capability["windows"],
        serde_json::json!(["main"]),
        "the main window only"
    );
    assert!(capability.get("remote").is_none(), "never remote");

    assert_eq!(names.len(), 31);
    assert_eq!(manifest, names, "build.rs <-> COMMANDS");
    assert_eq!(handler_names(), names, "generate_handler! <-> COMMANDS");
    assert_eq!(allowed, names, "capability <-> COMMANDS");
    // The old names are gone for good.
    for old in [
        "save_gmail_credentials",
        "delete_gmail_credentials",
        "clear_txt_files",
        "save_profile_template",
    ] {
        assert!(!names.contains(old), "{old}");
    }
}

/// The TypeScript command map is regenerated from the table; the test fails while the
/// committed file differs (commit the result). Every type it names must exist.
#[test]
fn the_typescript_command_map_is_generated_and_committed() {
    let table = command_table();
    let expected = commands_ts(&table);
    let known: BTreeSet<String> = std::fs::read_dir(repo("ui/src/lib/ipc/types"))
        .unwrap()
        .filter_map(|e| {
            let name = e.ok()?.file_name().to_string_lossy().into_owned();
            name.strip_suffix(".ts").map(str::to_string)
        })
        .collect();
    for (name, args, result) in &table {
        for word in format!("{args} {result}").split(|c: char| !c.is_ascii_alphanumeric()) {
            let is_type = word.chars().next().is_some_and(|c| c.is_ascii_uppercase());
            assert!(
                !is_type || ["Channel", "Record"].contains(&word) || known.contains(word),
                "{name}: unknown type {word}"
            );
        }
    }
    let path = repo("ui/src/lib/ipc/types/commands.ts");
    let current = std::fs::read_to_string(&path).unwrap_or_default();
    if current != expected {
        std::fs::write(&path, &expected).unwrap();
        panic!("regenerated {} - commit it", path.display());
    }
}

/// Safety invariant of the session window, as far as it can be checked without a window: it
/// downloads nothing, opens no further windows, checks every navigation against its portal
/// - and is in no capability (no command of the app is reachable from there).
#[test]
fn the_session_window_downloads_nothing_and_opens_no_window() {
    let session = read("src-tauri/src/session.rs");
    for required in [
        ".on_download(|_, _| false)",
        ".on_new_window(|_, _| NewWindowResponse::Deny)",
        "Session::allowed(site, url)",
    ] {
        assert!(session.contains(required), "session.rs: {required} missing");
    }
    // The profile folder (and with it the sign-in) belongs to the portal, not a fixed name.
    assert!(session.contains("jobalert_core::session_dir(site.portal)"));

    let capability: serde_json::Value =
        serde_json::from_str(&read("src-tauri/capabilities/main.json")).unwrap();
    assert_eq!(
        capability["windows"],
        serde_json::json!(["main"]),
        "portal windows are in no capability"
    );
}

/// Every run event carries the fields the generated TypeScript promises. The end once was
/// a newtype - with `tag = "type"` such a newtype merges with the event, `event.summary`
/// was undefined and the status bar stayed on "ready" after every run.
#[test]
fn run_events_serialise_as_the_types_say() {
    use jiff::Timestamp;
    use jobalert_core::pipeline::{RunEvent, RunKindName, RunSummary};

    let now = Timestamp::now();
    let event = serde_json::to_value(RunEvent::Finished {
        summary: Box::new(RunSummary::new(RunKindName::Fetch, true, now)),
    })
    .unwrap();
    assert_eq!(event["type"], "finished");
    assert!(event["summary"].is_object(), "end without summary: {event}");
    for field in [
        "run",
        "kind",
        "outcome",
        "dryRun",
        "startedAt",
        "finishedAt",
        "scan",
        "perPortal",
        "newJobs",
        "score",
        "export",
        "emptyAlerts",
    ] {
        assert!(
            event["summary"].get(field).is_some(),
            "{field} missing (null instead of missing): {event}"
        );
    }
    let ts = read("ui/src/lib/ipc/types/RunSummary.ts");
    for field in ["perPortal", "emptyAlerts", "finishedAt", "newJobs"] {
        assert!(ts.contains(field), "RunSummary.ts: {field}");
    }
    // Every run begins with its kind.
    let started = serde_json::to_value(RunEvent::Started {
        kind: RunKindName::Rescore,
    })
    .unwrap();
    assert_eq!(
        started,
        serde_json::json!({ "type": "started", "kind": "rescore" })
    );
    assert!(read("ui/src/lib/ipc/types/RunEvent.ts").contains("\"type\": \"started\""));
}
